- .github/workflows/package_upload.yml
- package/Makefile
72시간 테스트가 성공으로 끝나면 POS 데비안 패키지를 아티팩트로 업로드하는 액션 스크립트 작성
> [AWIBOF-5960] add pos debian package artifact upload action script

- tool/cli/cmd/root.go
Modify help message of the CLI client for the first commit.
Signed-off-by: Myoungjun Lee <jun20.lee@samsung.com>
> [AWIBOF-6025] Modify CLI help message

- .github/workflows/package_upload.yml
modify name of workflows (remove 'Test')
> [AWIBOF-6126] Update package_upload.yml

- test/unit-tests/journal_manager/replay/active_wb_stripe_replayer_test.cpp
> [AWIBOF-6083] Fix typo in comment

- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- src/include/pos_event_id.h
- tool/cli/cmd/grpcmgr/grpcmgr.go
- tool/cli/cmd/systemcmds/set_system_property.go
Change SETSYSTEMPROPERTY command to gRPC.
> [AWIBOF-6135] Change SETSYSTEMPROPERTY command to gRPC

- lib/CMakeLists.txt
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- src/telemetry/telemetry_air/telemetry_air_delegator.h
- test/unit-tests/telemetry/telemetry_air/telemetry_air_delegator_test.cpp
> [AWIBOF-6088] Release AIR 0.8.2-beta

- src/cli/delete_subsystem_command.cpp
- src/cli/list_qos_policies_command.cpp
- src/cli/list_volume_command.cpp
- src/cli/reset_qos_volume_policy_command.cpp
- src/cli/volume_info_command.cpp
- src/volume/i_volume_checker.h
- src/volume/i_volume_info_manager.h
- src/volume/i_volume_manager.h
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
- test/unit-tests/volume/i_volume_info_manager_mock.h
Signed-off-by: Jeongyeon Choi <jeddy.choi@samsung.com>
> [AWIBOF-6264] volume manager function hiding

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_perf_ci_single_numa.conf
- config/ibofos_for_perf_psd.conf
- config/ibofos_for_perf_psd_200GB.conf
- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/ibofos_for_vm_ci.conf
- config/ibofos_for_vm_ci_wt.conf
- config/pos.conf
- config/pos_for_aws.conf
- config/pos_for_pm_qos.conf
- config/pos_multi_array_normal.conf
- config/pos_multi_array_perf.conf
- src/master_context/default_configuration.h
- src/metafs/config/metafs_config_manager.cpp
- src/metafs/config/metafs_config_manager.h
- src/metafs/mim/meta_io_manager.cpp
- src/metafs/mim/metafs_io_request.cpp
- src/metafs/mim/metafs_io_request.h
- src/metafs/mim/metafs_io_scheduler.cpp
- src/metafs/mim/mio_handler.cpp
- test/integration-tests/metafs/lib/metafs_test_fixture.cpp
- test/unit-tests/metafs/config/metafs_config_manager_mock.h
- test/unit-tests/metafs/config/metafs_config_manager_test.cpp
- test/unit-tests/metafs/mim/metafs_io_request_mock.h
- test/unit-tests/metafs/mim/metafs_io_request_test.cpp
- Remove write_mpio_cache_enable config
- Add copy constructor for MetaFsIoRequest
> [AWIBOF-6175] Modify so that requests to Journal SSD can be combined

- doc/guides/cli/poseidonos-cli_volume_create.md
- src/cli/create_volume_command.cpp
- src/volume/i_volume_event_manager.h
- src/volume/i_volume_manager.h
- src/volume/volume.h
- src/volume/volume_base.cpp
- src/volume/volume_base.h
- src/volume/volume_creator.cpp
- src/volume/volume_creator.h
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
- src/volume/volume_meta_intf.cpp
- src/volume/volume_test.cpp
- test/unit-tests/volume/i_volume_event_manager_mock.h
- test/unit-tests/volume/i_volume_manager_mock.h
- test/unit-tests/volume/volume_base_test.cpp
- test/unit-tests/volume/volume_creator_test.cpp
- test/unit-tests/volume/volume_manager_mock.h
- test/unit-tests/volume/volume_manager_test.cpp
- tool/cli/cmd/messages/requests.go
- tool/cli/cmd/pos_cli_syntax.ebnf
- tool/cli/cmd/volumecmds/create_volume.go
Signed-off-by: Jeongyeon Choi <jeddy.choi@samsung.com>
> [AWIBOF-6263] save volume attribute at volume meta, add cli arg

- test/README.md
Signed-off-by: Youngjin Yu <youngjin2.yu@samsung.com>
> [AWIBOF-6199] Remove gen_ut command from test/'s readme doc

- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- src/cli/grpc_cli_server.h
- tool/cli/cmd/arraycmds/add_spare.go
- tool/cli/cmd/grpcmgr/grpcmgr.go
Change ADDSPARE command to gRPC.
> [AWIBOF-6306] Change ADDSPARE command to gRPC

- README.md
Revise README.md.
Correct grammatical errors and revise the overall writing.
> [AWIBOF-6301] Revise README.md

- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- tool/cli/cmd/arraycmds/delete_array.go
- tool/cli/cmd/arraycmds/remove_spare.go
- tool/cli/cmd/grpcmgr/grpcmgr.go
Change REMOVESPARE/DELETEARRAY to gRPC.
Revise the warning message for DELETEARRAY command.
> [AWIBOF-6323] Change REMOVESPARE/DELTEARRAY to gRPC

- src/telemetry/telemetry_client/grpc_global_publisher.cpp
> [AWIBOF-6287] remove constraint regarding maximum number of request size

- test/system/filesystem/filebench_test.py
> [AWIBOF-6365] Fix filebench test script error

- doc/development/telemetry/ID_RULES.md
- doc/development/telemetry/METRICS.md
> [AWIBOF-6392] modify duplicated id in MD file

- src/metafs/mim/mio.cpp
- src/metafs/mim/mpio.cpp
- src/metafs/mim/mpio.h
- src/metafs/mim/mpio_allocator.cpp
- src/metafs/mim/write_mpio.cpp
- test/unit-tests/metafs/mim/mpio_test.cpp
> [AWIBOF-6278] Refactor mpio cache functions

- doc/development/telemetry/METRICS.md
- src/cli/array_info_command.cpp
- src/cli/command_processor.cpp
- src/cli/list_array_command.cpp
- src/sys_info/space_info.cpp
- src/sys_info/space_info.h
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- src/telemetry/telemetry_id.h
- src/volume/volume_interface.cpp
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
Add Array/Volume usage telemetry metrics
> Awibof 6255 sds

- lib/CMakeLists.txt
- lib/fio-3.28.patch
- lib/spdk-21.04.patch
> [AWIBOF-6395] fio version up

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_perf_ci_single_numa.conf
- config/ibofos_for_perf_psd.conf
- config/ibofos_for_perf_psd_200GB.conf
- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/ibofos_for_vm_ci.conf
- config/ibofos_for_vm_ci_wt.conf
- config/pos.conf
- config/pos_for_aws.conf
- config/pos_for_pm_qos.conf
- config/pos_multi_array_normal.conf
- config/pos_multi_array_perf.conf
- src/master_context/default_configuration.h
- src/metafs/config/metafs_config_manager.cpp
- src/metafs/config/metafs_config_manager.h
- test/integration-tests/metafs/lib/metafs_test_fixture.cpp
- test/unit-tests/metafs/config/metafs_config_manager_mock.h
- test/unit-tests/metafs/config/metafs_config_manager_test.cpp
> [AWIBOF-6423] Add WRR configs for metafs

- src/admin/smart_log_meta_io.cpp
- src/admin/smart_log_meta_io.h
- test/unit-tests/admin/smart_log_meta_io_mock.h
- test/unit-tests/admin/smart_log_meta_io_test.cpp
> [AWIBOF-6364] Fix segfault caused by not waiting for the request to be completed

- doc/development/telemetry/ID_RULES.md
- doc/development/telemetry/METRICS.md
- src/cli/smart_log_command.cpp
- src/include/pos_event_id.h
- src/main/poseidonos.cpp
- src/resource_checker/resource_checker.cpp
- src/resource_checker/smart_collector.cpp
- src/resource_checker/smart_collector.h
- src/telemetry/telemetry_id.h
> [AWIBOF-6257] add telemetry entries

- src/allocator/context_manager/segment_ctx/segment_ctx.cpp
- src/allocator/context_manager/segment_ctx/segment_ctx.h
- src/metadata/block_map_update.cpp
- test/integration-tests/segmentCtx/CMakeLists.txt
- test/integration-tests/segmentCtx/segment_ctx_integration_test.cpp
- test/integration-tests/segmentCtx/segment_ctx_integration_test.h
code changes:
Added integration test for segment management
> [AWIBOF-5248] [Ckpt.Perf] SegmentCtx Integration Test

- src/resource_checker/smart_collector.cpp
> [AWIBOF-6444] Fix nvme ctrlr check logic

- test/system/benchmark/config/pm_fio_kdd.json
- test/system/benchmark/config/pm_fio_normal.json
- test/system/benchmark/config/vm_fio_precommit.json
- test/system/benchmark/scenario/fio_normal.py
> [AWIBOF-6393] Enable CI sustained test

- src/gc/victim_stripe.cpp
- src/include/pos_event_id.h
> [AWIBOF-6483] Modify flood trace

- test/system/benchmark/scenario/fio_sustain.py
> [AWIBOF-6393] Update CI sustained test

- src/gc/gc_flush_completion.cpp
- src/gc/gc_flush_completion.h
- src/gc/gc_flush_submission.cpp
- src/gc/gc_flush_submission.h
- src/gc/gc_map_update_completion.cpp
- src/gc/gc_map_update_completion.h
- src/gc/gc_map_update_request.cpp
- src/gc/gc_map_update_request.h
- src/include/smart_ptr_type.h
- src/meta_service/i_meta_updater.h
- src/metadata/gc_map_update.cpp
- src/metadata/gc_map_update.h
- src/metadata/meta_event_factory.cpp
- src/metadata/meta_event_factory.h
- src/metadata/meta_updater.cpp
- src/metadata/meta_updater.h
- test/unit-tests/gc/gc_flush_completion_test.cpp
- test/unit-tests/gc/gc_flush_submission_test.cpp
- test/unit-tests/gc/gc_map_update_completion_test.cpp
- test/unit-tests/gc/gc_map_update_request_test.cpp
- test/unit-tests/meta_service/i_meta_updater_mock.h
- test/unit-tests/metadata/gc_map_update_test.cpp
- test/unit-tests/metadata/meta_event_factory_mock.h
- test/unit-tests/metadata/meta_event_factory_test.cpp
- test/unit-tests/metadata/meta_updater_test.cpp
> [AWIBOF-6480] Change Stripe used by gc to be handled using shared_ptr

- src/resource_checker/resource_checker.cpp
- src/resource_checker/smart_collector.cpp
- src/resource_checker/smart_collector.h
> [AWIBOF-6495] Convert from spdk library to ubio

- config/air.cfg
- config/air_ci.cfg
- src/cli/command_processor.cpp
- src/cli/update_event_wrr_policy_command.h
- src/device/unvme/unvme_drv.cpp
- src/event_scheduler/backend_event_minimum_policy.cpp
- src/event_scheduler/backend_event_ratio_policy.cpp
- src/include/backend_event.h
- src/metafs/storage/pstore/mss_io_completion.cpp
- src/metafs/storage/pstore/mss_io_completion.h
- src/metafs/storage/pstore/mss_on_disk.cpp
- test/unit-tests/metafs/storage/pstore/mss_io_completion_test.cpp
- to solve performance problem during checkpoint
> [AWIBOF-6500] Add BackendEvent_JournalIO

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_perf_ci_single_numa.conf
- config/ibofos_for_perf_psd.conf
- config/ibofos_for_perf_psd_200GB.conf
- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/ibofos_for_vm_ci.conf
- config/ibofos_for_vm_ci_wt.conf
- config/pos.conf
- config/pos_for_aws.conf
- config/pos_for_pm_qos.conf
- config/pos_multi_array_normal.conf
- config/pos_multi_array_perf.conf
- doc/development/telemetry/METRICS.md
- src/journal_manager/config/journal_configuration.cpp
- src/journal_manager/config/journal_configuration.h
- src/journal_manager/journal_manager.cpp
- src/journal_manager/log_buffer/log_write_context.h
- src/journal_manager/log_write/log_write_handler.cpp
- src/journal_manager/log_write/log_write_handler.h
- src/master_context/default_configuration.h
- src/telemetry/telemetry_id.h
- test/unit-tests/journal_manager/config/journal_configuration_test.cpp
- test/unit-tests/journal_manager/log_write/log_write_handler_mock.h
- test/unit-tests/journal_manager/log_write/log_write_handler_test.cpp
> [AWIBOF-6497] Add metrics for journal count and time spent

- src/metafs/config/metafs_config_manager.h
- src/metafs/metafs_service.cpp
- src/metafs/mim/metafs_io_scheduler.cpp
- src/metafs/mim/metafs_io_scheduler.h
- src/metafs/mim/mio_handler.cpp
- src/metafs/mim/mpio_handler.cpp
- src/metafs/mim/mpio_handler.h
- test/integration-tests/metafs/lib/metafs_test_fixture.cpp
- test/unit-tests/metafs/config/metafs_config_manager_mock.h
- test/unit-tests/metafs/config/metafs_config_manager_test.cpp
- test/unit-tests/metafs/mim/meta_io_manager_test.cpp
- test/unit-tests/metafs/mim/metafs_io_scheduler_test.cpp
- test/unit-tests/metafs/mim/mio_handler_test.cpp
- test/unit-tests/metafs/mim/mpio_handler_test.cpp
- added weight getter to metafs config manager
> [AWIBOF-6542] Apply wrr to MetaFsIoScheduler and MpioHandler

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_perf_ci_single_numa.conf
- config/ibofos_for_perf_psd.conf
- config/ibofos_for_perf_psd_200GB.conf
- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/ibofos_for_vm_ci.conf
- config/ibofos_for_vm_ci_wt.conf
- config/pos.conf
- config/pos_for_aws.conf
- config/pos_for_pm_qos.conf
- config/pos_multi_array_normal.conf
- config/pos_multi_array_perf.conf
- src/journal_manager/config/journal_configuration.cpp
- src/journal_manager/config/journal_configuration.h
- src/master_context/default_configuration.h
- test/unit-tests/journal_manager/config/journal_configuration_test.cpp
> [AWIBOF-6541] Add number_of_log_groups config for journal

- doc/development/telemetry/METRICS.md
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- src/telemetry/telemetry_id.h
> [AWIBOF-6529] Add journal type to telemetry air delegator

- src/resource_checker/smart_collector.cpp
> [AWIBOF-6552] remove unnecessary logic

- src/Makefile
- src/array/array.cpp
- src/array/rebuild/i_array_rebuilder.h
- src/array/rebuild/rebuild_context.h
- src/include/rebuild_type.h
- src/rebuild/array_rebuild.cpp
- src/rebuild/array_rebuilder.cpp
- src/rebuild/array_rebuilder.h
- src/rebuild/rebuild_behavior.cpp
- src/rebuild/rebuild_behavior.h
- src/rebuild/recovery_methods/Makefile
- src/rebuild/recovery_methods/quick_recovery.cpp
- src/rebuild/recovery_methods/quick_recovery.h
- src/rebuild/recovery_methods/rebuild_recovery.cpp
- src/rebuild/recovery_methods/rebuild_recovery.h
- src/rebuild/recovery_methods/recovery_base.cpp
- src/rebuild/recovery_methods/recovery_base.h
- src/rebuild/segment_based_rebuild.cpp
- src/rebuild/stripe_based_race_rebuild.cpp
- test/unit-tests/array/rebuild/i_array_rebuilder_mock.h
- test/unit-tests/rebuild/array_rebuild_test.cpp
- test/unit-tests/rebuild/array_rebuilder_mock.h
- test/unit-tests/rebuild/array_rebuilder_test.cpp
- test/unit-tests/rebuild/partition_rebuild_test.cpp
Signed-off-by: minjoon.ahn <minjoon.ahn@samsung.com>
Objectives: Need to support quick-rebuild
Changes: Design changes to add restoration function through copy
> [AWIBOF-5035] Design change to add quick rebuild operation

- doc/guides/cli/poseidonos-cli_subsystem_create.md
- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- src/include/pos_event_id.h
- tool/cli/cmd/grpcmgr/grpcmgr.go
- tool/cli/cmd/messages/requests.go
- tool/cli/cmd/subsystemcmds/create_subsystem.go
Change CREATESUBSYSTEM command to gRPC.
- Rename some message fields to camel case. 
- Refactor codes
- Update docs
- Add event logs
> [AWIBOF-6610] Change CREATESUBSYSTEM command to gRPC

- config/air.cfg
- config/air_ci.cfg
- doc/development/telemetry/METRICS.md
- src/admin/admin_command_handler.cpp
- src/io/frontend_io/aio.cpp
- src/io/frontend_io/read_completion.cpp
- src/io/frontend_io/read_completion_for_partial_write.cpp
- src/io/frontend_io/read_submission.cpp
- src/io/frontend_io/unvmf_io_handler.cpp
- src/io/frontend_io/write_completion.cpp
- src/io/frontend_io/write_submission.cpp
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- src/telemetry/telemetry_id.h
Signed-off-by: Jeongyeon Choi <jeddy.choi@samsung.com>
> [AWIBOF-6503] add frontend io_raw telemetry metric

- src/journal_manager/config/journal_configuration.cpp
- src/journal_manager/config/journal_configuration.h
- src/journal_manager/replay/active_wb_stripe_replayer.cpp
- src/rocksdb_log_buffer/rocksdb_log_buffer.cpp
> [AWIBOF-6621] Fix coverity issues

- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- src/include/pos_event_id.h
- tool/cli/cmd/grpcmgr/grpcmgr.go
- tool/cli/cmd/subsystemcmds/add_listener.go
Change ADDLISTERNER command to gRPC.
Refactor code and enhance event logging.
> [AWIBOF-6630] Change ADDLISTENER command to gRPC

- Makefile
- lib/CMakeLists.txt
- lib/spdk-22.01.1.patch
- src/io/general_io/command_timeout_handler_test/command_timeout_handler_test.cpp
- src/spdk_wrapper/nvme.cpp
- test/CMakeLists.txt
- test/unit-tests/device/uram/uram_drv_test.cpp
- test/unit-tests/qos/qos_spdk_manager_test.cpp
- test/unit-tests/utils/spdk_util.cpp
- test/unit-tests/utils/spdk_util.h
spdk v22.01.1 버전 업데이트 지원을 위해 수정한 리뷰입니다. 
다행히 pos와 conflict나는 부분은 많지 않았고 새로운 spdk patch와 makefile일부를 수정하였습니다.
precommit 돌려보기 위해 우선적으로 pr을 올렸고 merge 전에 postcommit, long term 등 모든 테스트를 수동으로 돌리고 merge되는것이 안전할 것 같습니다.
> [AWIBOF-5977] Update vanilla SPDK versino from v21.04 to V22.01.1

- src/include/pos_event_id.h
- src/io/frontend_io/block_map_update_request.cpp
- src/io/frontend_io/block_map_update_request.h
- src/journal_manager/journal_writer.cpp
- src/journal_manager/journal_writer.h
- src/logger/logger.h
- test/unit-tests/logger/logger_mock.h
- test/unit-tests/logger/logger_test.cpp
- applied the trace to journal and io
> [AWIBOF-6637] Add POS_TRACE that works when the status is changed

- src/volume/volume_detacher.cpp
- src/volume/volume_list.cpp
- tool/dump/gdb_scripts/volume_io.py
bug fix
Jeongyeon Choi <jeddy.choi@samsung.net>
> [AWIBOF-6678] bug fix for pending io

- doc/guides/cli/poseidonos-cli_subsystem_list.md
- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- tool/cli/cmd/displaymgr/display_response.go
- tool/cli/cmd/grpcmgr/grpcmgr.go
- tool/cli/cmd/subsystemcmds/list_subsystem.go
Change SUBSYSTEMINFO command to gRPC.
Fix typos in docs.
> [AWIBOF-6630] Change SUBSYSTEMINFO command to gRPC

- Makefile
- lib/CMakeLists.txt
Add opentelemetry building process into CMakeLists.txt
Add opentelemetry header & library into Makefile
> [AWIBOF-6662] Enables opentelemetry API/SDK (v1.4.1)

- src/allocator/context_manager/block_allocation_status.cpp
> [AWIBOF-6544] Remove unnecessary logs

- src/pos_replicator/grpc_volume_management.cpp
- src/pos_replicator/grpc_volume_management.h
- src/pos_replicator/posreplicator_manager.cpp
- src/pos_replicator/replicator_volume_subscriber.cpp
- src/pos_replicator/replicator_volume_subscriber.h
moved to prevent duplicate construction
Jeongyeon Choi <jeddy.choi@samsung.net>
> [AWIBOF-6699] move GrpcVolumeManagement construct point

- tool/cli/cmd/arraycmds/create_array.go
- tool/cli/cmd/arraycmds/create_array_test.go
- tool/cli/cmd/arraycmds/general.go
- tool/cli/cmd/displaymgr/display_request.go
- tool/cli/cmd/displaymgr/display_response.go
Refactor CREATEARRAY command.
Revise the tests.
> [AWIBOF-6710] Refactor CREATEARRAY command

- src/io/frontend_io/write_submission.cpp
Allocate write stripe Chunk unit in write though mode
> [AWIBOF-6694] allocate write stripe with chunk unit, not 1

- tool/cli/cmd/arraycmds/add_spare.go
- tool/cli/cmd/arraycmds/add_spare_test.go
- tool/cli/cmd/arraycmds/autocreate_array.go
- tool/cli/cmd/arraycmds/autocreate_array_test.go
- tool/cli/cmd/arraycmds/create_array_test.go
- tool/cli/cmd/arraycmds/delete_array.go
- tool/cli/cmd/arraycmds/delete_array_test.go
- tool/cli/cmd/arraycmds/list_array.go
- tool/cli/cmd/arraycmds/list_array_test.go
- tool/cli/cmd/arraycmds/mount_array.go
- tool/cli/cmd/arraycmds/mount_array_test.go
- tool/cli/cmd/arraycmds/remove_spare.go
- tool/cli/cmd/arraycmds/remove_spare_test.go
- tool/cli/cmd/arraycmds/unmount_array.go
- tool/cli/cmd/arraycmds/unmount_array_test.go
Refactor CLI client and tests for array commands.
> [AWIBOF-6726] Refactor CLI client and tests for array commands

- src/allocator/context_manager/segment_ctx/segment_ctx.cpp
- src/allocator/context_manager/segment_ctx/segment_ctx.h
- src/event_scheduler/meta_update_call_back.cpp
- src/event_scheduler/meta_update_call_back.h
- src/journal_manager/log_write/log_write_handler.cpp
- src/metadata/block_map_update.cpp
- src/metadata/block_map_update.h
- src/metadata/gc_map_update.cpp
- src/metadata/gc_map_update.h
- src/metadata/meta_event_factory.cpp
- src/metadata/meta_event_factory.h
- src/metadata/segment_context_updater.cpp
- src/metadata/segment_context_updater.h
- src/metadata/stripe_map_update.cpp
- src/metadata/stripe_map_update.h
- test/integration-tests/allocator/context_manager_integration_test.cpp
- test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_mock.h
- test/unit-tests/allocator/i_segment_ctx_mock.h
- test/unit-tests/metadata/block_map_update_test.cpp
- test/unit-tests/metadata/gc_map_update_test.cpp
- test/unit-tests/metadata/segment_context_updater_mock.h
- test/unit-tests/metadata/segment_context_updater_test.cpp
- test/unit-tests/metadata/stripe_map_update_test.cpp
code changes:
added meta update callback to enable versioned segment context.
Signed-off-by: dh.ihm <dh.ihm@samsung.com>
> [AWIBOF-4305] Versioned Segment Context Checkpoint

- src/journal_manager/checkpoint/checkpoint_handler.cpp
- src/journal_manager/checkpoint/checkpoint_handler.h
- src/journal_manager/checkpoint/checkpoint_manager.cpp
- src/journal_manager/checkpoint/checkpoint_manager.h
- src/journal_manager/journal_manager.cpp
- src/mapper/mapper.cpp
- src/mapper/mapper.h
- src/mapper/stripemap/stripemap_manager.cpp
- src/mapper/vsamap/vsamap_manager.cpp
- test/unit-tests/journal_manager/checkpoint/checkpoint_handler_test.cpp
- test/unit-tests/journal_manager/checkpoint/checkpoint_manager_test.cpp
- test/unit-tests/journal_manager/checkpoint/checkpoint_meta_flush_completed_test.cpp
- test/unit-tests/mapper/vsamap/vsamap_manager_test.cpp
> [AWIBOF-6729] Change meta logs to add arrayId

- test/unit-tests/journal_manager/log_write/log_write_handler_test.cpp
Code changes:
added unit test for meta update callback.
> [AWIBOF-6739] Versioned Segment Context unit test

- src/cpu_affinity/affinity_config_parser.cpp
- src/cpu_affinity/affinity_viewer.cpp
- src/cpu_affinity/affinity_viewer.h
- src/cpu_affinity/cpu_set_generator.h
event reactor를 위한 affinity option 추가.
> [AWIBOF-6759] add affinity configuration for reactor only option

- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- tool/cli/cmd/displaymgr/display_response.go
Change subsystemList to subsystemlist in protobuf message
for CI test, which parses the JSON response of SUBSYSTEMLIST and SUBSYSTEMINFO
commands.
> [AWIBOF-6722] Change subsystemList to subsystemlist for CI test

- lib/CMakeLists.txt
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- src/telemetry/telemetry_air/telemetry_air_delegator.h
- test/unit-tests/telemetry/telemetry_air/telemetry_air_delegator_test.cpp
> [AWIBOF-6456] Refactor telemetry_air_delegator

- lib/spdk-22.01.1.patch
- src/cpu_affinity/affinity_config_parser.cpp
- src/cpu_affinity/affinity_config_parser.h
- src/cpu_affinity/affinity_manager.cpp
- src/spdk_wrapper/caller/spdk_nvmf_caller.cpp
- src/spdk_wrapper/caller/spdk_nvmf_caller.h
- SPDK: Change nvmf connection for event reactor
- POS: Add interface to send event reactor set
> [AWIBOF-6775] Change nvmf connection for event reactor, Add interface

- src/journal_manager/journal_manager.cpp
- src/journal_manager/log_buffer/i_versioned_segment_context.h
- src/journal_manager/log_buffer/versioned_segment_ctx.h
- test/integration-tests/allocator/context_manager_integration_test.cpp
- test/integration-tests/journal/checkpoint_integration_test.cpp
- test/integration-tests/journal/fake/array_info_mock.cpp
- test/integration-tests/journal/fake/array_info_mock.h
- test/integration-tests/journal/fixture/journal_manager_test_fixture.h
- test/integration-tests/journal/journal_manager_spy.h
- test/unit-tests/allocator/context_manager/context_manager_test.cpp
- test/unit-tests/journal_manager/log_buffer/i_versioned_segment_context_mock.h
- test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_mock.h
Code changes:
added integration test for versioned segment context updating.
Signed-off-by: dh.ihm <dh.ihm@samsung.com>
> [AWIBOF-6800] Add versioned segment context integration test

- lib/spdk-22.01.1.patch
> [AWIBOF-6777] Update volume latency profiling

- src/journal_manager/checkpoint/checkpoint_manager.cpp
- src/journal_manager/checkpoint/checkpoint_manager.h
- src/journal_manager/journal_manager.cpp
- src/journal_manager/journal_manager.h
- src/journal_manager/log_buffer/log_write_context_factory.cpp
- src/journal_manager/log_buffer/log_write_context_factory.h
- src/journal_manager/log_buffer/map_update_log_write_context.cpp
- src/journal_manager/log_buffer/map_update_log_write_context.h
- test/integration-tests/allocator/context_manager_integration_test.cpp
- test/integration-tests/journal/log_buffer_integration_test.cpp
- test/integration-tests/rocksdb/rocksdb_log_buffer_integration_test.cpp
- test/unit-tests/journal_manager/checkpoint/checkpoint_manager_mock.h
- test/unit-tests/journal_manager/checkpoint/checkpoint_manager_test.cpp
- test/unit-tests/journal_manager/journal_manager_test.cpp
- test/unit-tests/journal_manager/log_buffer/log_write_context_factory_mock.h
- test/unit-tests/journal_manager/log_buffer/log_write_context_factory_test.cpp
- test/unit-tests/journal_manager/log_buffer/map_update_log_write_context_test.cpp
- test/unit-tests/journal_manager/log_write/log_write_handler_test.cpp
Code changes:
remove journal sequence controller lock.
> [AWIBOF-5176] remove journal sequence controller lock.

- test/integration-tests/metafs/lib/metafs_test_fixture.cpp
> [AWIBOF-6837] Add code to reset metafs service instance

- test/system/lib/cli.py
exception handlings of cli for functional test scripts when the cli client cannot connect to the server
> [AWIBOF-6896] exception handlings of cli for functional test scripts

- .github/workflows/script/unit/ut_build_run_unittest.sh
Fix UT script.
Create /etc/pos if not exist.
> [AWIBOF-6773] Fix UT script

- src/array/array.cpp
- src/array/ft/method.h
- src/array/ft/raid10.cpp
- src/array/ft/raid10.h
- src/array/ft/raid5.cpp
- src/array/ft/raid5.h
- src/array/ft/raid6.cpp
- src/array/ft/raid6.h
- src/array/partition/stripe_partition.cpp
- src/array/partition/stripe_partition.h
- src/helper/enumerable/query.h
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY_DURING_IO.py
- test/functional_requirements/fault_tolerance/REBUILD_ONE_DEV_WHEN_TWO_DEVS_FAIL_IN_RAID6_ARRAY_DURING_IO.py
- test/functional_requirements/simple_io/IO_DEGRADED_IN_RAID10_W_TWO_FAULT_DEVS.py
- test/functional_requirements/simple_io/IO_DEGRADED_IN_RAID6_W_TWO_FAULT_DEVS.py
- test/regression/fault_tolerance_ci_test_for_raid6.sh
- test/system/lib/pos.py
- test/unit-tests/array/ft/raid10_mock.h
- test/unit-tests/array/ft/raid5_mock.h
- test/unit-tests/helper/query_test.cpp
Signed-off-by: minjoon.ahn <minjoon.ahn@samsung.com>
> [AWIBOF-6898] RAID6 rebuild validation and tests added

- config/pos_multi_array_normal.conf
- src/event/pos_event.yaml
- src/metafs/config/metafs_config_manager.cpp
- src/metafs/config/metafs_config_manager.h
- src/metafs/include/metafs_service.h
- src/metafs/metafs_service.cpp
- src/metafs/mim/metafs_io_scheduler.cpp
- src/metafs/mim/metafs_io_scheduler.h
- test/unit-tests/metafs/config/metafs_config_manager_mock.h
- test/unit-tests/metafs/config/metafs_config_manager_test.cpp
- test/unit-tests/metafs/include/metafs_service_test.cpp
metafs io scheduler를 구성하는데 문제가 있는 경우 log를 출력하고 assert 발생하도록 수정
> [AWIBOF-6916] Modify operation of considering meta scheduler setting

- test/system/benchmark/config/pm_fio_kdd.json
- test/system/benchmark/config/pm_fio_sustain.json
- test/system/benchmark/config/vm_fio_verify.json
> [AWIBOF-6954] Update ARION v0.4.0-alpha

- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/pos_multi_array_normal.conf
Add Reactor only option for PM CI test
> [AWIBOF-6942] Add reactor only config for Physical Machine's CI test

- config/publication_list_default.yaml
- src/array/array.cpp
- src/array/array.h
- src/array/array_metrics_publisher.cpp
- src/array/array_metrics_publisher.h
- src/array/state/array_state.cpp
- src/array/state/array_state.h
- src/array/state/array_state_publisher.cpp
- src/array/state/array_state_publisher.h
- src/array_models/interface/i_array_state_subscriber.h
- src/cli/array_info_command.cpp
- src/cli/command_processor.cpp
- src/cli/list_array_command.cpp
- src/sys_event/volume_event_publisher.cpp
- src/sys_info/space_info.h
- src/sys_info/space_info_publisher.cpp
- src/sys_info/space_info_publisher.h
- src/telemetry/telemetry_id.h
- test/unit-tests/array/state/array_state_mock.h
array capacity 관련 metric 추가 건 + 기존 array state publish 구조 refactoring 입니다
> [AWIBOF-6880] added array capacity metrics for telemetry

- lib/CMakeLists.txt
> [AWIBOF-7003] Deploy AIR v0.8.5-beta

- src/array/service/io_recover/io_recover.cpp
- src/array/service/io_recover/io_recover.h
- src/array/service/io_translator/io_translator.cpp
- src/array/service/io_translator/io_translator.h
- src/array/state/array_state_publisher.cpp
- src/array/state/array_state_publisher.h
- src/array_components/array_components.cpp
- src/device/unvme/unvme_drv.cpp
- src/sys_info/space_info_publisher.cpp
- src/sys_info/space_info_publisher.h
> [AWIBOF-7051] fixed memory leak issues

- src/allocator/allocator.cpp
- src/event/pos_event.yaml
- src/journal_manager/journal_manager.cpp
- src/journal_manager/journal_manager.h
- src/journal_manager/replay/read_log_buffer.cpp
- src/journal_manager/replay/replay_handler.cpp
- src/mapper/mapper.cpp
- src/metadata/metadata.cpp
- test/regression/spor_ci_test.sh
- test/system/spor/SPOR_BASIC_0.py
- test/unit-tests/journal_manager/journal_manager_test.cpp
- test/unit-tests/metadata/metadata_test.cpp
> [AWIBOF-6929] Make metadata module init/dispose be idempotent

- src/allocator/context_manager/context_manager.cpp
- src/allocator/context_manager/context_manager.h
- src/allocator/i_context_manager.h
- src/journal_manager/journal_manager.cpp
- test/integration-tests/journal/fake/i_context_manager_mock.h
- test/unit-tests/allocator/context_manager/context_manager_mock.h
- test/unit-tests/allocator/i_context_manager_mock.h
- test/unit-tests/journal_manager/journal_manager_test.cpp
code changes:
Allow duplicated flush command if pos use journal disabled configuration.
> [AWIBOF-7047] modified flush command handling.

- src/array/array.cpp
- test/functional_requirements/fault_tolerance/QUICK_REBUILD_RESUME_TEST_AFTER_SPOR.py
Signed-off-by: minjoon.ahn <minjoon.ahn@samsung.com>
test cases added and minor bug fix when resuming rebuilds
> [AWIBOF-7056] updated test cases for resuming quick rebuild after spor

- src/event/pos_event.yaml
- src/pos_replicator/posreplicator_manager.cpp
- src/pos_replicator/replicator_volume_subscriber.cpp
Jeongyeon Choi <jeddy.choi@samsung.net>
> [AWIBOF-7060] add shutdown process at Replicator Volume Subscriber

- src/journal_manager/journal_manager.cpp
- src/metafs/include/meta_file_context.h
- src/metafs/mai/metafs_file_control_api.cpp
- src/metafs/mai/metafs_wbt_api.cpp
- test/integration-tests/allocator/context_manager_integration_test.cpp
- test/unit-tests/metafs/mai/metafs_io_api_test.cpp
- test/unit-tests/metafs/mai/metafs_wbt_api_test.cpp
- test/unit-tests/metafs/mim/metafs_io_request_test.cpp
- test/unit-tests/metafs/mim/metafs_io_scheduler_test.cpp
> [AWIBOF-7021] Remove memory leak of meta modules

- .github/workflows/package_upload.yml
push로 트리거 될 때에 workflow_dispatch의 값을 참조하지 않고 checkout하도록 변경
> [AWIBOF-7068] action workflow push trigger fix

- test/regression/fault_tolerance_ci_test_for_raid6_multi_device.sh
Add delay for   detach_device and add_spare
> [AWIBOF-7066] Fix raid6 multi-device CI test

- src/main/poseidonos.cpp
Jeongyeon Choi <jeddy.choi@samsung.net>
> [AWIBOF-7071] bugfix for memory leak

- test/regression/fault_tolerance_ci_test_for_raid6_multi_device.sh
> [AWIBOF-7066] Update RAID6 CI test

- .github/workflows/72_hour-release.yml
- .github/workflows/coverage-release.yml
- .github/workflows/longterm-release.yml
- .github/workflows/script/build_setup.sh
> [AWIBOF-7076] schedule based job is enabled

- src/allocator/context_manager/context_manager.h
- fixed unexpected behavior during checkpoint
> [AWIBOF-7070] Change initialize order of ContextManager

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_vm_ci.conf
Qos Config has old config. So we will change into new config (reactor used only)
> [AWIBOF-7079] QoS config fix

- config/air.cfg
- config/air_ci.cfg
- src/cli/command_processor.cpp
- src/cli/update_event_wrr_policy_command.h
- src/device/unvme/unvme_drv.cpp
- src/event_scheduler/backend_event_minimum_policy.cpp
- src/event_scheduler/backend_event_ratio_policy.cpp
> [AWIBOF-7073] Fix assertion due to new backend event type

- src/metafs/storage/mss.cpp
- src/metafs/storage/mss.h
- src/metafs/storage/pstore/issue_write_event.h
- src/metafs/storage/pstore/mss_on_disk.cpp
- src/metafs/storage/pstore/mss_on_disk.h
- test/unit-tests/metafs/storage/pstore/issue_write_event_test.cpp
> [AWIBOF-7094] Fix to prevent error messages from occurring due to unused callback

- src/admin/smart_log_meta_io.cpp
- src/meta_file_intf/rocksdb_metafs_intf.cpp
- src/metafs/mim/metafs_io_scheduler.cpp
- src/telemetry/telemetry_client/pos_metric.cpp
- src/telemetry/telemetry_client/pos_metric.h
- src/telemetry/telemetry_client/telemetry_client.cpp
- Added initialization to fix coverity issue
- Coverity 이슈 관련 처리를 추가했습니다.
Signed-off-by: Sanghyeok Park <sang7.park@samsung.com>
> [AWIBOF-7100] fixed coverity issue

- src/spdk_wrapper/event_framework_api.cpp
- src/spdk_wrapper/event_framework_api.h
> leave information for reactor events

- src/journal_manager/journal_writer.cpp
- added initialization
Signed-off-by: Sanghyeok Park <sang7.park@samsung.com>
> Coverity fixed

- src/qos/monitoring_manager_array.cpp
- src/wbt/update_config_wbt_command.cpp
- test/functional_requirements/fault_tolerance/REBUILD_DETACH_ANOTHER_DEV_DURING_REBUILD_IN_RAID6_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_DETACH_TARGET_DURING_REBUILD_AND_ADD_SPARE.py
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID10_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY_AND_DETACH_TARGET_DURING_REBUILDING.py
- test/functional_requirements/fault_tolerance/REBUILD_IN_RAID6_ARRAY_DURING_IO.py
- test/functional_requirements/fault_tolerance/REBUILD_ONE_DEV_WHEN_TWO_DEVS_FAIL_IN_RAID6_ARRAY_DURING_IO.py
- test/functional_requirements/fault_tolerance/REBUILD_RESUME_TEST_AFTER_SPOR_IN_RAID6_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID10_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID6_ARRAY.py
- test/functional_requirements/fault_tolerance/REBUILD_TWO_DEVS_CONCURRENTLY_IN_RAID6_ARRAY_AND_DETACH_TARGET_DURING_REBUILDING.py
- test/functional_requirements/fault_tolerance/REBUILD_TWO_FAULT_DEVS_AND_ONE_SPARE_DEV_IN_RAID6_ARRAY.py
Add timeout to RAID6 coverage tests.
> [AWIBOF-7116] Fix RAID6 coverage tests

- src/resource_checker/smart_collector.cpp
> [AWIBOF-7125] Fix coverity issue 40585 & 40588

- src/debug/debug_info.cpp
- src/spdk_wrapper/event_framework_api.cpp
> [AWIBOF-7127] fix coverity issue

- src/metafs/storage/pstore/issue_write_event.h
- there were too many logs about retrying meta io
> [AWIBOF-7115] Change common macro to mfs macro to write log

- src/journal_manager/log_write/log_write_handler.cpp
- src/journal_manager/log_write/log_write_handler.h
- test/unit-tests/journal_manager/log_write/log_write_handler_test.cpp
> [AWIBOF-6988] Change metrics of journal log counts to publish all the log groups

- Makefile
> [AWIBOF-7128] change release v0.12.0-rc0 version name

- .github/workflows/script/code_coverage.sh
quote mark is set to calculate coverage properly
> [AWIBOF-7079] quote mark is not properly set in coverage test

- src/cli/command_processor.cpp
> [AWIBOF-7129] Fix coverity issue

- config/pos.conf
- config/publication_list_default.yaml
- src/master_context/default_configuration.h
- src/telemetry/telemetry_client/telemetry_publisher.cpp
- Change metric names
- Add config for selective publication
> [AWIBOF-7134] Fix telemetry selective publication bug

- package/Makefile
- package/src/DEBIAN/postinst
- package/src/DEBIAN/prerm
+ POS Package install 시 pos-prometheus 시 DB를 초기화
+ POS Package install 시 pos-prometheus container 삭제
> [AWIBOF-7140] Modifies behavior of pos-prometheus container in package

- config/ibofos_for_perf_ci.conf
- config/ibofos_for_perf_ci_single_numa.conf
- config/ibofos_for_perf_psd.conf
- config/ibofos_for_psd_ci.conf
- config/ibofos_for_psd_ci_wt.conf
- config/ibofos_for_vm_ci.conf
- config/ibofos_for_vm_ci_wt.conf
- config/longterm.conf
- config/pos.conf
- config/pos_for_aws.conf
- config/pos_for_fio_rebuild.conf
- config/pos_for_pm_qos.conf
- config/pos_multi_array_normal.conf
- config/pos_multi_array_perf.conf
- src/master_context/default_configuration.h
- reduced the sizes to smaller
> [AWIBOF-7143] Change mio and mpio pool capacity

- src/journal_manager/checkpoint/checkpoint_handler.cpp
- fixed race condition of checkpointCompletionCallback
Signed-off-by: Sanghyeok Park <sang7.park@samsung.com>
> [AWIBOF-7152] R3 performance test fix

- src/cli/create_qos_volume_policy_command.cpp
- src/cli/create_qos_volume_policy_command.h
- src/cli/list_qos_policies_command.cpp
- src/qos/qos_manager.cpp
- src/qos/qos_manager.h
- src/volume/volume_creator.cpp
- src/volume/volume_creator.h
- src/volume/volume_manager.cpp
- test/system/io_path/qos_cli_accept.py
1) qos create 와 volume create 시 max bw / min bw 등을 체크하던 코드를 일원화
2) 기존에 있었던 이슈(qos list 시 vol1만 확인되던 이슈)를 fix
> [SHPOS-909] QoS max bw should not be accepted for out of range

- src/allocator/context_manager/allocator_file_io.cpp
- src/journal_manager/log_buffer/journal_log_buffer.cpp
- src/mapper/map/event_mpage_async_io.cpp
- src/mapper/map/map_io_handler.cpp
- src/mapper/reversemap/reverse_map.cpp
- src/meta_file_intf/async_context.cpp
- src/meta_file_intf/async_context.h
- test/unit-tests/meta_file_intf/async_context_mock.h
- test/unit-tests/meta_file_intf/async_context_test.cpp
> [AWIBOF-7171] Add more fail log to get meta request info

- Makefile
Update POS version info. (v0.11.1)
> [AWIBOF-7256] Update POS version info. (v0.11.1)

- config/pos.conf
- src/Makefile
- src/array_components/array_components.cpp
- src/array_components/array_components.h
- src/debug/debug_info.cpp
- src/debug/debug_info.h
- src/main/poseidonos.cpp
- src/main/poseidonos.h
- test/CMakeLists.txt
- test/unit-tests/pos_replicator/CMakeLists.txt
- test/unit-tests/utils/mock_builder.cpp
[Revieweee] 
- Review 목적: Test scope에서 pos_replicator관련 코드는 제외시키기 위한 코드 및 build 스크립트 수정
- 참고 문서: AWIBOF-7159
- 주요 review 파일: array_component, debuginfo, poseidonos
- 검증 방법 또는 TC: IT/UT, Coverage
[Reviewer] 
- Checklist : product code 내에서 pos_replicator관련 초기화 함수 및 변수를 제거하였습니다. 관련하여 mock_builder도 함께 수정이 됐는지 이상이 없는지 같이 봐주시면 감사하게씃ㅂ니다
> [AWIBOF-7159] Disable pos_replicator in test scope

- src/io/frontend_io/unvmf_io_handler.cpp
- src/pos_replicator/posreplicator_manager.cpp
Fix typo suppoered to supported
Fix misuse of variable arrayName and volumeName
> [AWIBOF-7260] Fix typo and misuse of variable

- README.md
Add make install step as optional to README.md.
> [AWIBOF-7259] Add make install step to README.md

- src/qos/qos_manager.cpp
- test/system/io_path/qos_cli_accept.py
> [SHPOS-954] Fix max iops boundary fail

- .github/workflows/package_upload.yml
Tag 생성에 대한 package version 수정 (Commit hash 제거)
> [AWIBOF-7307] tagged package version

- src/array/ft/raid6.cpp
optimization of RAID6 by minimizing memory allocation
remove some memory dynamic allocation path in RAID6
> [SHPOS-923] Optimization of RAID6 by minimizing memory allocation

- src/gc/flow_control/flow_control.cpp
- src/gc/flow_control/flow_control.h
- src/gc/gc_flush_submission.cpp
- src/gc/gc_flush_submission.h
- src/gc/gc_stripe_manager.cpp
force flush 발생시 token reset로직 추가
> [AWIBOF-7328] reset tokens after force flush

- lib/spdk-22.01.1.patch
> [SHPOS-964] Fix invalid memory access when host issues trim command

- src/telemetry/telemetry_client/grpc_global_publisher.cpp
- tool/pos-exporter/cmd/subscriber.go
Fix Server / Client grpc Send/Recv Max Size.
> [ AWIBOF-7353 ] Fix Air Metric grpc  overflow

- src/device/base/io_context.cpp
- src/device/base/io_context.h
- src/device/unvme/unvme_drv.cpp
- src/device/unvme/unvme_ssd.cpp
- src/device/unvme/unvme_ssd.h
- src/telemetry/telemetry_air/telemetry_air_delegator.cpp
- test/unit-tests/device/unvme/unvme_drv_test.cpp
- test/unit-tests/device/unvme/unvme_io_context_mock.h
> [SHPOS-965] Update device related telemetry label value

- src/Makefile
- src/event/pos_event.yaml
- src/gc/copier.cpp
- src/gc/copier_read_completion.cpp
- src/gc/force_flush_locker/Makefile
- src/gc/force_flush_locker/force_flush_locker.cpp
- src/gc/force_flush_locker/force_flush_locker.h
- src/gc/force_flush_locker/force_flush_locker_busy_state.cpp
- src/gc/force_flush_locker/force_flush_locker_busy_state.h
- src/gc/force_flush_locker/force_flush_locker_normal_state.cpp
- src/gc/force_flush_locker/force_flush_locker_normal_state.h
- src/gc/force_flush_locker/force_flush_locker_state.h
- src/gc/gc_flush_submission.cpp
- src/gc/gc_stripe_manager.cpp
- src/gc/gc_stripe_manager.h
gc force flush로 인한 thread간 동기화 이슈 해결을 위한 lock 구조 적용
> [SHPOS-975] Race condition handling for GC force flush

- Makefile
Update POS version info. (v0.11.2)
> [AWIBOF-7365] Update POS version info. (v0.11.2)

- Makefile
Update version info (v0.12.0-rc3)
> [AWIBOF-7359] Update version info (v0.12.0-rc3)

- doc/guides/cli/poseidonos-cli_system_set-property.md
- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- tool/cli/cmd/systemcmds/get_system_property.go
- tool/cli/cmd/systemcmds/set_system_property.go
- tool/cli/cmd/systemcmds/start_system.go
- tool/cli/cmd/systemcmds/start_system_test.go
- tool/cli/cmd/systemcmds/stop_system.go
- tool/cli/cmd/systemcmds/system_info.go
Refactor system commands
- Refactor code
- Refactor tests
- Revise help messages
- Update docs
> [AWIBOF-7397] Refactor system commands

- src/allocator/context_manager/context_flush_completion.cpp
- src/allocator/context_manager/context_flush_completion.h
- src/allocator/context_manager/context_manager.cpp
- src/journal_manager/checkpoint/checkpoint_handler.cpp
code changes:
Modified the code to call reset flushed info always.
> [SHPOS-993] reset flush info after unmount volume

- package/src/etc/poseidonos.service
- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/allocator/context_manager/context_flush_completion.cpp
- src/allocator/context_manager/context_flush_completion.h
- src/allocator/context_manager/context_manager.cpp
- src/cli/command_processor.cpp
- src/journal_manager/checkpoint/checkpoint_handler.cpp
- test/unit-tests/allocator/context_manager/context_manager_test.cpp
- tool/cli/cmd/displaymgr/display_response.go
- tool/cli/cmd/displaymgr/display_response_test.go
release 코드를 main에 merge 하기 위한 pr입니다.
cli.pb.cc코드에서 하나의 conflict가 있었는데 
명준님께서 더 최근에(5일전) 반영하신 코드 부분을 반영해서 conflict를 해결했습니다. (https://github.com/poseidonos/poseidonos/pull/549)
> Merge release to main ww47

- src/array_mgmt/array_manager.cpp
Reset MBR logic updated
level0 Test case 실패로 해당 로직원복
> [AWIBOF-1001] Reset MBR logic updated

- Makefile
Update version info (v0.12.0-rc4)
> [AWIBOF-7454] Update version info (v0.12.0-rc4)

- src/volume/volume_manager.cpp
> [AWIBOF-7457] Fix volume manager coverity issue

- src/array/ft/raid6.cpp
- src/array/ft/raid6.h
> Restore RAID6 galois field table caching

- README.md
- script/pkgdep.sh
Add libssl-dev to pkgdep.sh
Signed-off-by: yunho.yang <yunho.yang@samsung.com>
> [AWIBOF-7472] Fix for OpenTelemetry build issue

- src/array/state/array_state.cpp
- test/unit-tests/array/state/array_state_test.cpp
fix recoverable condition
can be recovered during rebuild
> Shpos 1013 fix recoverable condition

- Makefile
Update version info (v0.12.0-rc5)
> [AWIBOF-7469] Update version info (v0.12.0-rc5)

- test/system/benchmark/config/pm_fio_sustain.json
> [AWIBOF-7493] Enable ASan and dump at fio sustain test

- test/system/benchmark/config/pm_fio_sustain.json
> [AWIBOF-7493] Enable ASan and dump at CI R3 test

- proto/cli.proto
- proto/generated/cpp/cli.grpc.pb.cc
- proto/generated/cpp/cli.grpc.pb.h
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/command_processor.h
- src/cli/grpc_cli_server.cpp
- tool/cli/cmd/grpcmgr/grpcmgr.go
- tool/cli/cmd/qoscmds/create_qos_volume_policy.go
- tool/cli/cmd/qoscmds/reset_qos_volume.go
Change CLI Server and Client code to change RESETQOSVOLUMEPOLICY to gRPC
> Change RESETQOSVOLUMEPOLICY command to gRPC

- config/air.cfg
- config/air_ci.cfg
- lib/CMakeLists.txt
- Update AIR to v0.8.7-beta
- Update ARION to latest main commit(1ae1dee7)
> [AWIBOF-7506] Update AIR and ARION

- Makefile
Update version info (v0.12.0-rc6)
> [AWIBOF-7538] Update version info (v0.12.0-rc6)

- Makefile
Update version info (v0.12.0-rc7)
> [AWIBOF-7568] Update version info (v0.12.0-rc7)

- doc/guides/cli/poseidonos-cli_volume_create.md
- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/volume/i_volume_event_manager.h
- src/volume/i_volume_manager.h
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
- src/volume/volume_test.cpp
- test/unit-tests/volume/i_volume_event_manager_mock.h
- test/unit-tests/volume/i_volume_manager_mock.h
- test/unit-tests/volume/volume_manager_mock.h
- test/unit-tests/volume/volume_manager_test.cpp
- tool/cli/cmd/volumecmds/create_volume.go
Signed-off-by: Jeongyeon Choi <jeddy.choi@samsung.com>
> [AWIBOF-7566] add cli argument

- doc/guides/telemetry/telemetry_guide.md
Add telemetry set up guide.
This guide introduces how to set up telemetry
using POS Telemetry, Prometheus, and Grafana.
Based on the response by @dshwpark in https://github.com/poseidonos/poseidonos/issues/640
> [AWIBOF-7578] Add telemetry set up guide

- src/metafs/mim/mio.cpp
- src/metafs/mim/mpio_allocator.cpp
- src/metafs/mim/mpio_allocator.h
- test/unit-tests/metafs/common/fifo_cache_mock.h
- test/unit-tests/metafs/mim/mpio_allocator_test.cpp
- changed MpioAllocator::IsFullyCached() to IsCacheFull()
- added unit test for the method
> [AWIBOF-7485] Change a method name and add unit tests

- Makefile
- src/journal_manager/checkpoint/checkpoint_handler.cpp
- src/mapper/stripemap/stripemap_manager.cpp
- src/mapper/vsamap/vsamap_manager.cpp
- Changed to enqueue callback event after all jobs done in MapFlushDone
- Added error code to log
- Updated version info
> Shpos 1019 map flush fail bugfix

- src/journal_manager/log_write/buffer_offset_allocator.cpp
- src/journal_manager/log_write/buffer_offset_allocator.h
- src/journal_manager/status/i_log_buffer_status.h
- src/journal_manager/status/journal_status_provider.cpp
- test/unit-tests/journal_manager/status/i_log_buffer_status_mock.h
- test/unit-tests/journal_manager/status/journal_status_provider_test.cpp
Signed-off-by: cheolho.kang <cheolho.kang@samsung.com>
> [AWIBOF-7414] Add WBT to print numFilledLogs each log groups

- config/pos_multi_array_fast_sustain_perf.conf
- src/array/array.h
- src/io/frontend_io/write_submission.cpp
- src/metadata/meta_updater.cpp
- src/volume/i_volume_info_manager.h
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
- src/wbt/set_write_bypass_wbt_command.cpp
- src/wbt/set_write_bypass_wbt_command.h
- src/wbt/wbt_cmd_handler.cpp
- src/wbt/wbt_command_opcode.h
- test/integration-tests/journal/fake/array_info_mock.cpp
- test/integration-tests/journal/fake/array_info_mock.h
- test/system/benchmark/config/pm_fio_fast_sustain_multi_array.json
- test/system/benchmark/scenario/fio_fast_sustain.py
- test/unit-tests/array_models/interface/i_array_info_mock.h
- test/unit-tests/volume/i_volume_info_manager_mock.h
- Add WriteBypass flag to do only complete callback without writing data to SSD
- Add WBT command to set WritBypass flags in runtime
- Add ARION test scenario to make GC sustain
Signed-off-by: dageon.hwang <dageon.hwang@samsung.com>
> [AWIBOF-6629] Add write bypass feature to make fast GC sustain

- src/volume/volume_meta_intf.cpp
- src/volume/volume_meta_intf.h
> [AWIBOF-7647] Hide malloc and free using unique_ptr

- src/journal_manager/config/journal_configuration.cpp
- src/journal_manager/config/journal_configuration.h
- src/journal_manager/journal_manager.cpp
- src/journal_manager/journal_manager.h
- src/mapper/mapper.cpp
- src/metadata/metadata.cpp
- src/metadata/metadata.h
- src/metafs/mai/metafs_file_control_api.h
- src/metafs/metafs.cpp
- src/metafs/metafs.h
- src/metafs/metafs_file_intf.cpp
- src/metafs/tool/fio/meta_scheduler.cpp
- src/wbt/wbt_metafs_cmd_handler.cpp
- test/integration-tests/journal/journal_configuration_spy.cpp
- test/integration-tests/journal/journal_configuration_spy.h
- test/integration-tests/metafs/lib/test_metafs.h
- test/integration-tests/metafs/metafs_functional_test.cpp
- test/integration-tests/metafs/metafs_io_test.cpp
- test/integration-tests/metafs/metafs_wbt_test.cpp
- test/unit-tests/journal_manager/config/journal_configuration_mock.h
- test/unit-tests/journal_manager/config/journal_configuration_test.cpp
- test/unit-tests/journal_manager/journal_manager_mock.h
- test/unit-tests/metadata/metadata_test.cpp
- test/unit-tests/metafs/include/metafs_mock.h
- test/unit-tests/metafs/metafs_file_intf_test.cpp
- test/unit-tests/metafs/metafs_test.cpp
- test/unit-tests/metafs/tool/fio/meta_scheduler_test.cpp
> [AWIBOF-7681] Hide api classes outside MetaFs

- tool/cli/cmd/arraycmds/list_array.go
- tool/cli/cmd/grpcmgr/grpcmgr.go
Changed the list_array.go file to use Kouros
Remove SendArrayInfo and SendListArray functions from grpcmgr.go file in CLI
> LIST Array and Array Info Command Changed to GRPC

- lib/spdk-22.01.1.patch
add write with streamid command to spdk for multistream
Signed-off-by: Yongjin Lee <yong7.lee@samsung.com>
> [AWIBOF-7481] Add spdk write with stream id

- tool/cli/cmd/subsystemcmds/add_listener.go
- tool/cli/cmd/subsystemcmds/create_subsystem.go
- tool/cli/cmd/subsystemcmds/create_transport.go
- tool/cli/cmd/subsystemcmds/delete_subsystem.go
- tool/cli/cmd/subsystemcmds/list_subsystem.go
ADDLISTENER, CREATESUBSYSTEM, CREATETRANSPORT, DELETESUBSYSTEM, LISTSUBSYSTEM commands changed
> Subsytem Commands changed to Kouros

- src/metafs/metafs.cpp
> [AWIBOF-7874] Modify the location of initializing meta file control api

- src/cli/grpc_cli_server.cpp
- src/debug_lib/README
- src/debug_lib/debug_info.cpp
- src/debug_lib/debug_info_maker.h
- src/debug_lib/debug_info_maker.hpp
- src/debug_lib/debug_info_queue.h
- src/debug_lib/debug_info_queue.hpp
- src/gc/copier.cpp
- src/gc/copier.h
- test/unit-tests/debug_lib/debug_info_maker_mock.h
- tool/dump/gdb_scripts/debug_info.py
We can produce json File from debug Info.
But flush timing is something not designed. So, I just commit for serializing its own code.
> [AWIBOF-7750] Serializing Debug Info

- src/cli/command_processor.cpp
Socket based commands had a try..catch wrapper to handle exception. So, It was returning code 40000 if any exception was generated
Added a try catch for WBT commands so that the status code is 40000 when the exception occurs
> [AWIBOF-7900] C-Precommit VM Test Fail

- src/mapper/reversemap/reverse_map_io.cpp
- src/mapper/reversemap/reverse_map_io.h
- removed access to deleted instance due to race condition
> [AWIBOF-7948] Modify ReverseMapIo to avoid accessing data fields after deleting the instance

- src/mapper/reversemap/reverse_map_io.cpp
> [AWIBOF-7968] Fix REVMAP_IO_ERROR during reverse map io

- src/journal_manager/journal_manager.cpp
- src/journal_manager/log_buffer/versioned_segment_ctx.cpp
- src/mapper/reversemap/reversemap_manager.cpp
- src/mapper/reversemap/reversemap_manager.h
- src/meta_file_intf/mock_file_intf.h
- src/meta_file_intf/rocksdb_metafs_intf.cpp
- src/metafs/config/metafs_config_manager.cpp
- src/metafs/mim/mio_handler.cpp
- src/metafs/mim/mpio_handler.cpp
- src/volume/volume_replicate_property_updater.cpp
- fixed initialization issues
- fixed to access array correctly
> [AWIBOF-8087] Fix coverity issues

- src/array_mgmt/array_manager.cpp
- src/array_mgmt/array_manager.h
- src/array_mgmt/interface/i_array_mgmt.h
- src/cli/command_processor.cpp
- src/gc/copier.h
- src/main/poseidonos.cpp
- src/signal_handler/signal_handler.cpp
- src/signal_handler/signal_handler.h
- test/regression/tc_lib_ci.sh
- test/regression/volume_ci_test.sh
- test/unit-tests/array_mgmt/interface/i_array_mgmt_mock.h
Normal shutdown can be incurred by only one signal or CLI
- signal handler : SIGTERM or SIGQUIT will unmount array and stop process.
If failed condition (i.e. rebuild in progress) happenend, retry internally, so signal will not be failed.
- CLI : unmount array and stop process happend. it will be failed if Unmount Array is failed.
> [AWIBOF-7929] Shutdown from signal handler and stop cli

- src/cli/command_processor.cpp
- src/event/pos_event.yaml
- src/main/poseidonos.cpp
- src/main/poseidonos.h
System Start & Stop progress log
> [AWIBOF-7917] Update log for system start and stop

- script/pkgdep.sh
python module 중 skbuild 가 없어서 build fail 나는 현상입니다.
> [AWIBOF-8133] add installation of essential python modules

- src/event/pos_event.yaml
- src/sys_event/volume_event_publisher.cpp
> [AWIBOF-7925, 7927] add volume event progress

- .github/workflows/postcommit.yml
- .github/workflows/script/signal_test/signal_postcommit.sh
- src/cli/command_processor.cpp
- src/cli/grpc_cli_server.cpp
- src/cli/grpc_cli_server.h
- src/include/poseidonos_interface.h
- src/lib/signal_mask.cpp
- src/lib/signal_mask.h
- src/main/poseidonos.cpp
- src/main/poseidonos.h
- src/signal_handler/signal_handler.cpp
- test/regression/signal_ci_test.sh
- test/regression/signal_during_rebuild.sh
- test/regression/tc_lib_ci.sh
- test/regression/volume_ci_test.sh
- test/system/io_path/mdts_detach_test/mdts_detach_unittest.cpp
- test/system/io_path/ubio_error_test/ubio_error_test.cpp
- test/unit-tests/lib/signal_mask_test.cpp
- tool/library_unit_test/library_unit_test.cpp
- tool/library_unit_test/library_unit_test.h
CLI 도중엔 signal이 못들어오게, signal 도중엔 CLI가 못들어오게 한다. 
signal 을 한번 받으면 main thread의 condition variable이 trigger 되고, 그 main thread가 CLI 의 server를 shutdown 하면서, signal 도중에 CLI 처리를 하지 않게 된다.
> cli signal synchronization

- lib/spdk-22.01.1.patch
- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/list_listener_command.cpp
- src/cli/list_subsystem_command.cpp
- tool/cli/cmd/displaymgr/display_response.go
subsystem, listener 생성 시 uuid  자동 생성 및 저장
pos cli 에도 uuid 추가
> [AWIBOF-7937] Add subsystem & listener uuid to cli

- proto/cli.proto
- proto/generated/cpp/cli.pb.cc
- proto/generated/cpp/cli.pb.h
- src/cli/command_processor.cpp
- src/cli/mount_volume_command.cpp
- src/network/nvmf_target.cpp
- src/network/nvmf_target.h
- src/network/nvmf_target_spdk.cpp
- src/restore/restore_manager.cpp
- src/restore/restore_manager.h
- src/sys_event/volume_event.h
- src/volume/i_volume_event_manager.h
- src/volume/i_volume_manager.h
- src/volume/volume_deleter.cpp
- src/volume/volume_detacher.cpp
- src/volume/volume_interface.cpp
- src/volume/volume_manager.cpp
- src/volume/volume_manager.h
- src/volume/volume_mounter.cpp
- src/volume/volume_mounter.h
- src/volume/volume_test.cpp
- src/volume/volume_unmounter.cpp
- test/system/nvmf/target/cpp/nvmf_target_test.cpp
- test/system/nvmf/target/gtest/nvmf_target_gtest.cpp
- test/unit-tests/network/nvmf_target_mock.h
- test/unit-tests/network/nvmf_target_test.cpp
- test/unit-tests/volume/i_volume_manager_mock.h
- test/unit-tests/volume/volume_manager_mock.h
- test/unit-tests/volume/volume_manager_test.cpp
- test/unit-tests/volume/volume_mounter_test.cpp
Volume mount 할 때 nsid 를 지정할 수 있도록 interface 추가
restore.json 으로 volume 복구할 때 nsid 포함
> [AWIBOF-8099] Save and Restore volume nsid

- src/event/pos_event.yaml
- src/mapper/reversemap/reversemap_manager.cpp
- src/mapper/reversemap/reversemap_manager.h
- test/unit-tests/mapper/reversemap/reversemap_manager_test.cpp
- steps
= construct inverted map from the latest vsamap
= verify revMapInfos from the log buffer
= look up the rba
> [AWIBOF-7875] Change the logic of searching RBA during bringup

- src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
- src/allocator/context_manager/allocator_ctx/allocator_ctx.h
- src/allocator/context_manager/allocator_file_io.cpp
- src/allocator/context_manager/i_allocator_file_io_client.h
- src/allocator/context_manager/rebuild_ctx/rebuild_ctx.cpp
- src/allocator/context_manager/rebuild_ctx/rebuild_ctx.h
- src/allocator/context_manager/segment_ctx/segment_ctx.cpp
- src/allocator/context_manager/segment_ctx/segment_ctx.h
- src/journal_manager/replay/replay_block_map_update.cpp
- test/unit-tests/allocator/context_manager/allocator_ctx/allocator_ctx_mock.h
- test/unit-tests/allocator/context_manager/allocator_ctx/allocator_ctx_test.cpp
- test/unit-tests/allocator/context_manager/allocator_file_io_test.cpp
- test/unit-tests/allocator/context_manager/i_allocator_file_io_client_mock.h
- test/unit-tests/allocator/context_manager/rebuild_ctx/rebuild_ctx_mock.h
- test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_mock.h
- test/unit-tests/journal_manager/replay/replay_block_map_update_test.cpp
1. Save VSC with proto layout (AWIBOF-8200)
2. Replay block map though it's flushed before (AWIBOF-8123)
> Save vsc with proto

- src/io/frontend_io/unvmf_io_handler.cpp
- src/main/poseidonos.cpp
- src/signal_handler/deadlock_checker.cpp
- src/signal_handler/deadlock_checker.h
- src/signal_handler/signal_handler.cpp
- test/unit-tests/signal_handler/CMakeLists.txt
- test/unit-tests/signal_handler/deadlock_checker_test.cpp
- Each reactor increases heartbeat count, and checker thread check it periodically
- Unit tests are added
> [AWIBOF-8164] Check hang thread via heartbeat check

- src/array_mgmt/array_manager.cpp
- src/helper/string/hex_string_converter.h
> [AWIBOF-8236] fix static analysis issues

- src/signal_handler/signal_handler.cpp
- src/signal_handler/signal_handler.h
> [AWIBOF-8249] fix coverity error in signal handler

- src/device/device_manager.cpp
- src/io/frontend_io/write_submission.cpp
- src/journal_manager/checkpoint/checkpoint_handler.cpp
- src/journal_manager/log_buffer/versioned_segment_info.cpp
- src/journal_manager/replay/replay_stripe.cpp
- src/main/poseidonos.h
- src/metafs/mim/io_statistics.cpp
- src/wbt/wbt_metafs_cmd_handler.cpp
> [AWIBOF-8235] Fix coverity issues
