src/metafs/mim/meta_io_manager.cpp
Defect Analysis Result: Double resource release during exit.
=> Fix for Segmentation fault on processing exit #1

src/metafs/mai/metafs_io_api.cpp
Added initialization value for concurrentMetaFsTimeInterval
=> [AWIBOF-6010] coverity bug fixed

package/src/DEBIAN/postinst, package/src/DEBIAN/postrm
apt install poseidonos.deb 만 해서 upgrade 하려는 시나리오에서 postrm 스크립트로 인한 spdk lib 삭제 버그 수정
=> [AWIBOF-6140] upgrade package bugfix

src/cli/cli_server.cpp, src/logger/logger.cpp, tool/cli/script/build_cli.sh
Set TRACE log level to the default log level for major sink.
Change the levels of some events from INFO to DEBUG.
Add -p flag to mkdir to prevent error message when the directory exists.
=> [AWIBOF-6146] Set TRACE to the default log level for major sink

src/metafs/mim/mpio_allocator.h, test/unit-tests/metafs/mim/mio_test.cpp, test/unit-tests/metafs/mim/mpio_allocator_test.cpp
1. MpioAllocator::GetFreeCount(void)의 결과가 항상 0인 오류 수정
- 관련 tc 수정
2. mio test case 추가
=> [AWIBOF-6144] fix MpioAllocator::GetFreeCount() to return the intended value

src/allocator/context_manager/context_manager.cpp, src/allocator/context_manager/context_manager.h, src/allocator/context_manager/context_replayer.cpp, src/allocator/context_manager/gc_ctx/gc_ctx.cpp, src/allocator/context_manager/gc_ctx/gc_ctx.h, src/allocator/context_manager/segment_ctx/segment_ctx.cpp, src/allocator/context_manager/segment_ctx/segment_ctx.h, src/allocator/i_context_manager.h, src/allocator/i_segment_ctx.h, src/cli/array_info_command.cpp, src/gc/copier.cpp, src/metadata/gc_map_update.cpp, src/wbt/set_gc_threshold_wbt_command.cpp, test/integration-tests/allocator/context_manager_integration_test.cpp, test/integration-tests/journal/fake/i_context_manager_mock.h, test/unit-tests/allocator/context_manager/context_manager_mock.h, test/unit-tests/allocator/context_manager/context_manager_test.cpp, test/unit-tests/allocator/context_manager/context_replayer_test.cpp, test/unit-tests/allocator/context_manager/gc_ctx/gc_ctx_mock.h, test/unit-tests/allocator/context_manager/gc_ctx/gc_ctx_test.cpp, test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_mock.h, test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_test.cpp, test/unit-tests/allocator/i_context_manager_mock.h, test/unit-tests/allocator/i_segment_ctx_mock.h, test/unit-tests/gc/copier_test.cpp, test/unit-tests/metadata/gc_map_update_test.cpp
- Make SegmentCtx to implement ISegmentCtx interface
- Split GetCurrentGcMode and UpdateCurrentGcMode to remove not really needed
segment ctx call from outside
=> [AWIBOF-6059] Remove ISegmentCtx implementation in ContextManager

src/metafs/mai/metafs_io_api.cpp
- moved metric variables to proper position
Signed-off-by: Sanghyeok Park <sang7.park@samsung.com>
=> [AWIBOF-6298] move variables to proper position

proto/cli.proto, proto/generated/cpp/cli.grpc.pb.cc, proto/generated/cpp/cli.grpc.pb.h, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/command_processor.cpp, src/cli/command_processor.h, src/cli/grpc_cli_server.cpp, tool/cli/cmd/arraycmds/mount_array.go, tool/cli/cmd/arraycmds/unmount_array.go, tool/cli/cmd/grpcmgr/grpcmgr.go
Change MOUNTARRAY/UNMOUNTARRAY commands to gRPC.
Set CLI timeout to 30 seconds (this needs to be changed in the future).
=> [AWIBOF-6248] Change MOUNTARRAY/UNMOUNTARRAY commands to gRPC

doc/guides/cli/poseidonos-cli_array_create.md, tool/cli/cmd/arraycmds/create_array.go, tool/cli/cmd/pos_cli_syntax.ebnf
Add RAID6 to CLI.
Add RAID6 option to CLI client for future support.
Signed-off-by: Junghyun Hong <jh34.hong@samsung.com>
=> [AWIBOF-6320] Add RAID6 to CLI

tool/cli/cmd/globals/flags.go
Disable gRPC in CLI.
Currently, it is under development to change the communication
protocl for CLI from socket to gRPC. The problem is, timing issues
occur because some commands use gRPC and other commands use socket
(there are two CLI servers currently).
Therefore, until all the protocol is changed for every CLI command,
we disable the gRPC in CLI.
=> [AWIBOF-6325] Disable gRPC in CLI

proto/cli.proto, proto/generated/cpp/cli.grpc.pb.cc, proto/generated/cpp/cli.grpc.pb.h, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/autocreate_array_command.cpp, src/cli/command_processor.cpp, src/cli/command_processor.h, src/cli/grpc_cli_server.cpp, tool/cli/cmd/arraycmds/autocreate_array.go, tool/cli/cmd/displaymgr/display_response_test.go, tool/cli/cmd/grpcmgr/grpcmgr.go
Change AUTOCREATARRAY command to gRPC.
Change the underscore in the socket version of
AUTOCREATEARRAY to camel cases as the protobuf2json
uses camel case.
=> [AWIBOF-6330] Change AUTOCREATARRAY command to gRPC

doc/guides/cli/poseidonos-cli_array_autocreate.md, doc/guides/cli/poseidonos-cli_array_create.md, src/include/raid_type.h, tool/cli/cmd/arraycmds/autocreate_array.go, tool/cli/cmd/arraycmds/create_array.go
Add RAID6 options and examples to CLI array commands.
Add RAID6 options and examples to CREATEARRAY and AUTOCREATEARRAY commands for futher support.
Signed-off-by: Junghyun Hong <jh34.hong@samsung.com>
=> [AWIBOF-6320] Add RAID6 option to CLI array commands

doc/guides/cli/poseidonos-cli_cluster.md, doc/guides/cli/poseidonos-cli_cluster_lv.md, proto/cli.proto, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, tool/cli/cmd/clustercmds/general.go, tool/cli/cmd/clustercmds/list_ha_volume.go, tool/cli/cmd/displaymgr/display_response.go, tool/cli/cmd/grpcmgr/hadbmgr.go
Add LISTHAVOLUME command that displays the list of
volumes registered in HA cluster.
Name the command as LISTHAVOLUME to avoid the conflict to
LISTVOLUME command.
Refactor hadbmgr.go
Command execution:
lee@lee-Z390-DESIGNARE:~/Workspace/pos/pos-main/poseidonos/bin$ ./poseidonos-cli cluster lv
Id      |Name                |NodeName            |ArrayName           |Size                |Lastseen
------- |------------------- |------------------- |------------------- |------------------- |-------------------
1       |Volume1             |target0             |Array1              |1073741824          |2022-06-15T00:00:00Z
2       |Volume1             |clone0              |Array1              |1073741824          |2022-06-15T00:00:00Z
3       |Volume2             |clone1              |Array1 …
=> [AWIBOF-6360] Add LISTHAVOLUME command

tool/cli/cmd/pos_cli_syntax.ebnf
Add LISTHAVOLUME command syntax to CLI syntax as it was omitted.
=> [AWIBOF-6360] Add LISTHAVOLUME command to CLI syntax

tool/cli/cmd/grpcmgr/grpcmgr.go
Increase CLI request timeout from 30 seconds to 90 seconds.
With 30 seconds timeout, a deadline_exceeded event occurs
because some commands take longer than 30 seconds.
=> [AWIBOF-6531] Increase CLI request timeout to 90 seconds

proto/cli.proto, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/command_processor.cpp, src/cli/command_processor.h, tool/cli/cmd/displaymgr/display_response.go
Add BIOS, mainboard, baseboard, and processor information to SYSTEMINFO command.
Now the SYSTEMINFO command displays a wide range of information, which might be 
useful to the system administrator. 
The command will result as follows:
lee@lee-Z390-DESIGNARE:~/Workspace/pos/pos-main/poseidonos/bin$ ./poseidonos-cli system info
PosVersion            : v0.11.0-rc6
BiosVersion           : F8
BiosVendor            : American Megatrends Inc.
BiosReleaseDate       : 10/15/2019
SystemManufacturer    : Gigabyte Technology Co., Ltd.
SystemProductName     : Z390 DESIGNARE
SystemSerialNumber    : Default string
SystemUuid            : 032E02B4-0499-05FF-9806-9B0700080009
BaseboardManufacturer : Gigabyte Technology Co., Ltd.
BaseboardProductName  : Z390 DESIGNARE-CF
BaseboardSerialNumber : Default …
=> [AWIBOF-6545] Add BIOS, mainboard, baseboard, and processor information to SYSTEMINFO command

lib/spdk-22.01.1.patch
이전 spdk 버전에서는 thread 생성 시, 단일 core를 지정하여 인자로 넘겨 생성할 수 있었지만,
spdk 버전 업 되면서 특정 core에 pinning 되지 않는 방향으로 수정되어 spdk 내부 로직에의해 thread 가 생성되면 round-robin으로 reactor가 매핑되도록 변경되었습니다.
따라서 저희가 지정한 core가 아니라 자동적으로 core가 지정되면서 처음 poll_group create 호출을 시작하는 reactor 0에서 모든 thread-reactor pinning 정보를 저장하면 잘못된 정보가 저장되게 됩니다. 이 시점에는 해당 thread가 어떤 core에서 돌지 모르기 때문입니다.
따라서, .pinning 하는 함수를 안전하게 현재 돌고 있는 core에서 호출할 수 있도록 수정하였습니다.
=> [AWIBOF-6709] relocated set_tls_thread_to_reactor

proto/cli.proto, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/command_processor.cpp, tool/cli/cmd/displaymgr/display_response.go
Change subnqn to nqn in SUBSYSTEM commands,
because of the failures in CI tests.
TODO:
- To make the attribute name (nqn) consistent.
- To modify the CI tests accordingly.
=> [AWIBOF-6713] Change subnqn to nqn in SUBSYSTEM commands

proto/cli.proto, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/command_processor.cpp, tool/cli/cmd/subsystemcmds/create_subsystem.go
Change the name of a field from subnqn to nqn of CREATESUBSYSTEM command
to fix a CI failure issue.
=> [AWIBOF-6720] Change subnqn to nqn of CREATESUBSYSTEM command

lib/spdk-22.01.1.patch
spdk 22.01.1 does not use cpu_mask for its physical cores anymore.
So, we allocate area for poll_groups to know cpu id.
=> [AWIBOF-6762] apply numa dedicate option for spdk 22.01 update

tool/cli/cmd/grpcmgr/grpcmgr.go
Increase the CLI request timeout from 90 seconds to 180 seconds
as some commands take longer than 90 seconds.
TODO: the timeout value is arbitrarily set. We need a systemical
approach to decided the value.
=> [AWIBOF-6799] Set CLI request timeout to 180 seconds

src/cli/command_processor.cpp, src/cli/create_transport_command.cpp, src/cli/create_transport_command.h, src/helper/rpc/spdk_rpc_client.cpp, src/helper/rpc/spdk_rpc_client.h, src/include/nvmf_const.h, src/network/nvmf.cpp, src/network/transport_configuration.cpp, src/network/transport_configuration.h, test/unit-tests/helper/spdk_rpc_client_mock.h, test/unit-tests/network/transport_configuration_test.cpp
transport 생성 시 io unit size를 pos 에서 원하는 디폴트 값으로 설정하여 생성되도록 수정한 내용입니다. 
전에 한 번 리뷰를 받았던 내용인데 main에 누락되어서 다시 올립니다.
Signed-off-by: syeon.shin <syeon.shin@samsung.com>
=> [AWIBOF-5045] Add default io_unit_size for transport creation

src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_buffer/versioned_segment_info.cpp, src/journal_manager/log_buffer/versioned_segment_info.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp, test/unit-tests/journal_manager/log_buffer/versioned_segment_info_mock.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_info_test.cpp
Code changes:
added lock before reset, get values from versioned segment info.
Signed-off-by: dh.ihm <dh.ihm@samsung.com>
=> [AWIBOF-6845] added lock for versioned segment info.

src/device/device_manager.cpp
fix a deadlock issue while attaching device
attached device에 대한 mbr update가 실패할 시 deadlock발생
=> [AWIBOF-6878] fix a deadlock issue while attaching device

Makefile, package/src/DEBIAN/control, script/pkgdep.sh, test/CMakeLists.txt
Add Intel ISA-L library to POS. (https://github.com/intel/isa-l)
Add ISA-L packages to pkgdep.sh, Makefile, and package control file for RAID 6 support.
Signed-off-by: Junghyun Hong <jh34.hong@samsung.com>
=> [AWIBOF-6870] Add Intel ISA-L library to POS

.github/workflows/script/unit/ut_build_run_unittest.sh
Copy pos_event.yaml to the pos_conf directory for unit testing.
Previously, unit testing failed because pos_event.yaml was not copied
to the config directory. It was because unit testing script
did not execute $make install, which copies pos_event.yaml to the config
directory.
To fix the problem, this commit adds a copy command to the unit testing
script for github action.
=> [AWIBOF-6773] Copy pos_event.yaml for unit testing

doc/guides/cli/pos_railroad.html, doc/guides/cli/poseidonos-cli_telemetry.md, doc/guides/cli/poseidonos-cli_telemetry_set-property.md, doc/guides/cli/poseidonos-cli_volume_set-property.md, proto/cli.proto, proto/generated/cpp/cli.grpc.pb.cc, proto/generated/cpp/cli.grpc.pb.h, proto/generated/cpp/cli.pb.cc, proto/generated/cpp/cli.pb.h, src/cli/command_processor.cpp, src/cli/command_processor.h, src/cli/grpc_cli_server.cpp, src/telemetry/telemetry_client/telemetry_client.cpp, src/telemetry/telemetry_client/telemetry_client.h, tool/cli/cmd/grpcmgr/grpcmgr.go, tool/cli/cmd/pos_cli_syntax.ebnf, tool/cli/cmd/telemetrycmds/general.go, tool/cli/cmd/telemetrycmds/set_telemetry_property.go
Add SETTELEMETRYPROPERTY command, which updates the property of PoseidonOS telemetry module.
For now, only a flag to update metric publication list has been added to the command.
Add and update documents accordingly.
=> [AWIBOF-6972] Add SETTELEMETRYPROPERTY command

src/device/base/ublock_device.cpp, src/device/base/ublock_device.h, src/device/device_manager.cpp, src/device/uram/uram.cpp, src/device/uram/uram.h, test/unit-tests/device/base/ublock_device_mock.h, test/unit-tests/device/uram/uram_mock.h
Signed-off-by: sejun.kwon <sejun.kwon@samsung.com>
=> [AWIBOF-6942] Reactor Wrapping IO is moved from uram internal to device manager

tool/cli/cmd/displaymgr/display_response.go
Disable omitempty option when marshalling protobuf to json in CLI.
Previously, when a protobuf field is 0, the field is omitted in json response. It caused errors in testing scripts.
To fix the errors, this commit disables omitempty option.
=> [AWIBOF-7028] Disable omitempty when marshalling protobuf to json

config/pos_for_fio_rebuild.conf, src/array_components/array_components.cpp, src/array_components/array_components.h, src/cli/command_processor.cpp, src/debug/debug_info.cpp, src/debug/debug_info.h, src/event/pos_event.yaml, src/event_scheduler/callback.cpp, src/io_scheduler/io_dispatcher.cpp, src/io_scheduler/io_dispatcher.h, src/io_scheduler/io_dispatcher_submission.cpp, src/io_scheduler/io_dispatcher_submission.h, src/qos/qos_manager.cpp, src/rebuild/rebuild_methods/rebuild_write_done.cpp, test/unit-tests/array_components/array_components_test.cpp, test/unit-tests/io_scheduler/io_dispatcher_part2_test.cpp, test/unit-tests/utils/mock_builder.cpp
1) Each event has reactor's ratio which influence each bandwidth. 
2) Rebuild bandwidth is throttled by Rebuild impact 
3) If Host IO is idle, Rebuild bandwidth is not throttled.
Signed-off-by: sejun.kwon <sejun.kwon@samsung.com>
=> [AWIBOF-6869] control rebuild impact via io dispatcher

tool/cli/cmd/systemcmds/start_system.go
Not display start message (human readable) when --json-res flag is specified.
Previously, the human readable message caused some errors to test scripts, which parses the output of CLI as a json message.
=> [AWIBOF-7054] Not display start message when --json-res flag is specified

src/cli/cli_server.cpp, src/main/poseidonos.cpp
Fix memory leak by CLI-related modules.
=> [AWIBOF-7053] Fix memory leak by CLI-related modules

src/telemetry/telemetry_client/telemetry_publisher.cpp
Remove debug event logs from TelemetryPublisher because they reduce the readability of the event log.
=> [AWIBOF-7075] Remove debug event logs from TelemetryPublisher

src/allocator/context_manager/segment_ctx/segment_ctx.cpp
code changes:
fixed reset segments state function to update valid count and occuied stripe count (coverity issue).
=> [AWIBOF-7107] fix reset segments state function.

src/mapper/reversemap/reverse_map.cpp
fixed memory leak issue because the reference of shared_ptr is not removed
=> Awibof 7131 gc memory leak issue

.github/workflows/package_upload.yml, package/Makefile
workflow_call로 호출될 시 event_name이 caller workflow의 그것을 그대로 물려받는 특징이 있어
event_name을 workflow_call로 if를 통해 구별할 시에 인식을 못하는 문제 해결
=> [AWIBOF-7124] fix event_name for package build workflow call event

src/event_scheduler/backend_event_ratio_policy.cpp, src/event_scheduler/backend_event_ratio_policy.h
Just spotted a typo.
The variable is declared as 'workerarray' but it is used in constructor right below as 'workerArray'.
I don't know why the compiler does not complain.
I think it will be better to fix this anyway, though.
=> Fix capitalization typo

src/metafs/storage/pstore/issue_write_event.h
- if metadata write is requested when array is broken, a seg fault may occur in the mpio
- it is caused by enqueueing the mpio to the partial done enqueue twice (1st: self, 2nd: mss io completion)
- removed the first enqueue operation
=> [AWIBOF-7151] Remove enqueuing the mpio by itself when an error occurs due to the broken array

lib/spdk-22.01.1.patch
fio 수행중 간헐적으로 seg fault 발생한 이슈를 수정한 spdk patch 입니다.
fio 에서 multi thread에서 fio_cleanup을 호출하는데여기서 이미 free한 내용을 다시 free하면서 seg fault가 발생한 것으로 보입니다.
Signed-off-by: syeon.shin <syeon.shin@samsung.com>
=> [AWIBOF-7177] Fix fio segmentation fault during exiting the fio process

src/allocator/context_manager/context_manager.cpp, src/allocator/context_manager/context_manager.h, src/allocator/context_manager/segment_ctx/segment_ctx.cpp, src/allocator/context_manager/segment_ctx/segment_ctx.h, src/allocator/i_context_manager.h, src/allocator/i_segment_ctx.h, src/gc/copier.cpp, src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_buffer/versioned_segment_info.cpp, src/journal_manager/log_buffer/versioned_segment_info.h, src/metadata/meta_event_factory.cpp, src/metadata/segment_context_updater.cpp, src/metadata/segment_context_updater.h, test/integration-tests/journal/fake/i_context_manager_mock.h, test/unit-tests/allocator/context_manager/context_manager_mock.h, test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_mock.h, test/unit-tests/allocator/i_context_manager_mock.h, test/unit-tests/allocator/i_segment_ctx_mock.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_info_mock.h, test/unit-tests/metadata/metadata_test.cpp, test/unit-tests/metadata/segment_context_updater_mock.h
github ci R9 longterm 평가에서 GC 수행 중 발생하는 vsc valid block count under flow issue fix 입니다.
=> [AWIBOF-7196] reset vsc seg info after segment freed by GC.

test/system/lib/json_parser.py, test/system/longterm/72hour_test.py
문제 상황
: write back -> write through 로 CI 설정이 바뀌면서 mount시 소요되는 시간의 증가로 인해 cli timeout이 발생 하는 것으로 생각됩니다.
그로 인해 mount fail 이후 스크립트가 작동이 정상적으로 동작하지 않아 테스트가 실패한 것으로 생각됩니다.
해결 방법
- 스크립트에서 cli timeout시 발생하는 timeout을 크게 늘렸습니다.
- 숫자 자체는 우선은 작동하는지 확인하기 위해서 크게 늘려 놓은 것이라 추후에 세부 조정이 필요할 것으로 생각됩니다.
추가사항
(2022-10-25)
cli timeout 값이 정확한 측정값이 아니고 예측 값이기 때문에 혹시나 모를 또 다른 timeout이 발생할 수 있습니다.
그럴 경우에 대비해 cli response를 확인하는 코드에 예외 처리를 추가하여 cli timeout이 발생해도 POS가 dump를 생성 할 수 있도록 처리했습니다.
=> [AWIBOF-7290] fixed cli timeout value to larger value

tool/cli/patches/protojson_encode.patch, tool/cli/script/build_cli.sh
Fix CLI protojson patch bug.
Previously, CLI goes to panic when CLI displays int64. This is because the patch for jsonproto has a bug, which prints out int64 as uint64.
This commit fixes the bug above.
=> [AWIBOF-7309] Fix CLI protojson patch bug

Makefile, src/event/pos_event.yaml, src/journal_manager/log/log_buffer_parser.cpp, src/journal_manager/log/log_buffer_parser.h, src/journal_manager/log/log_event.h, src/journal_manager/replay/replay_handler.cpp, src/journal_manager/replay/replay_log_list.cpp, test/unit-tests/journal_manager/log/log_buffer_parser_test.cpp, test/unit-tests/journal_manager/log/log_list_mock.h, test/unit-tests/journal_manager/replay/replay_log_list_mock.h
[Revieweee] 
- Review 목적: footer에 기록된 resetedSequenceNumber보다 더 과거의 log가 발견된 case에 대한 error handling
- 참고 문서: SHPOS-945
- 주요 review 파일: log_buffer_parser.cpp, replay_log_list.cpp
- 검증 방법 또는 TC: IT/UT
[Reviewer] 
- Checklist 
1) ReplayLogList.EraseReplayLogGroup()에서 map 순회하며 log 지우는 알고리즘에 대한 검토
2) LogBufferParser의 logsFound를 sequence number 단위로 모아서 관리하고, 이를 통해 seqNumSeen 변수를 없앤 것에 대한 검토
3) UT 시나리오
=> [SHPOS-945] Fix log buffer parser to remove invalid logs 

test/system/longterm/72hour_test.py
fixed
- fixed invalid value to str
- fixed python parsing error
result
- 72hour test working
72hour test에서 CLI_MOUNT_TIMEOUT이 string이 아닌 int로 인식되어 생긴 문제를 수정했습니다.
=> [AWIBOF-7290] fixed by CI Test

tool/cli/cmd/displaymgr/display_response.go, tool/cli/cmd/displaymgr/display_response_test.go
Fix uint64 display bug when CLI prints out the response in a human readable form.
The bug is because total and used capacities were treated as strings in the CLI response display module.
This commit removes the type conversion on the capacities.
=> [SHPOS-959] Fix uint64 display bug for CLI display

src/allocator/context_manager/allocator_file_io.cpp, src/allocator/context_manager/context_io_manager.cpp, src/allocator/context_manager/context_manager.cpp, src/event/pos_event.yaml, src/journal_manager/checkpoint/checkpoint_handler.cpp, src/journal_manager/checkpoint/log_group_release_status.cpp, src/journal_manager/checkpoint/log_group_release_status.h, src/journal_manager/checkpoint/log_group_releaser.cpp, src/journal_manager/log_buffer/log_group_footer_write_event.cpp, src/journal_manager/log_buffer/reset_log_group.cpp, src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_write/buffer_offset_allocator.cpp, src/journal_manager/log_write/log_group_buffer_status.cpp, src/mapper/map/map_header.cpp, src/mapper/map/map_io_handler.cpp, src/mapper/stripemap/stripemap_manager.cpp, src/mapper/vsamap/vsamap_manager.cpp
Journaling, Checkpointing 과정의 log message들 리뷰하고 수정하였습니다.
structured logging 포맷대로 variable을 넣어보았습니다 ㅎㅎ
분석할 때 보실만 할지 의견 주시면 감사하겠습니다 ㅎㅎ 
**수정 결과 로그 (info level)** 
debug level 결과는 AWIBOF-7266 에 첨부해두었습니다.
```
[2022-11-04 05:15:13.102158709][31239][31240][62709859][3006][ info  ]  JOURNAL_READY - NONE (cause: NONE, solution: NONE, variables: status changed current_state:0, prev_state:4, prev_state_repeat_count:0 times), source: journal_writer.cpp:100 _CanBeWritten(), pos_version: v0.12.0-rc2
[2022-11-04 05:15:13.102177198][31239][31240][62709859][3039][ info  ]  JOURNAL_LOG_GROUP_ALLOCATED - NONE (cause: NONE, solution: NONE, variables: logGroupId:0), source: log_write/buffer_offset_allocator.cpp:129 AllocateBuffer(), pos_version: v0.12.0-rc2
[2022-11-04 …
```
=> Revise log messages

src/bio/volume_io.cpp, src/bio/volume_io.h, src/io/frontend_io/read_completion_for_partial_write.cpp, src/io/frontend_io/write_completion.cpp, src/io/frontend_io/write_completion.h, src/io/frontend_io/write_submission.cpp, src/io/frontend_io/write_submission.h, src/io/general_io/translator.cpp, src/io/general_io/translator.h, src/volume/i_volume_info_manager.h, src/volume/volume_manager.cpp, src/volume/volume_manager.h, test/unit-tests/bio/volume_io_test.cpp, test/unit-tests/io/frontend_io/read_completion_for_partial_write_test.cpp, test/unit-tests/io/frontend_io/read_submission_test.cpp, test/unit-tests/io/frontend_io/write_completion_test.cpp, test/unit-tests/io/frontend_io/write_submission_test.cpp, test/unit-tests/io/general_io/translator_test.cpp, test/unit-tests/volume/i_volume_info_manager_mock.h
IO Read/Write 과정에서 WT 여부를 알기 위해 Array의 GetInfo를 호출하는 부분이 있는데 GetInfo를 할 때마다 Lock을 잡게 되면서 해당 lock이 cpu의 30% 이상을 점유하게 되어 I/O path 상에 있는 GenInfo() 를 모두 제거 하였습니다.
WT enable여부는 array가 mount되는 시점에 volume manager 초기화되는데 이 부분에서 array의 wt 정보를 저장하고 io path에서는 volume manager를 통해 저장된 wt 정보를 읽는 형태로 수정하였습니다. 
Removed calling Array GetInfo() during io to avoid the impact of array lock
Signed-off-by: syeon.shin <syeon.shin@samsung.com>
=> [SHPOS-996] Fix performance degregation due to array info lock

src/array/ft/raid6.cpp, src/array/ft/raid6.h
Fix buffer size and array index access of Galois field matrix generation during RAID6 decoding.
=> [SHPOS-923] Fix buffer size and array index access during RAID6 decoding

src/array/rebuild/rebuild_method.cpp, src/include/array_config.h, src/resource_manager/buffer_pool.cpp, src/resource_manager/buffer_pool.h, test/unit-tests/resource_manager/buffer_pool_mock.h
minimize lock overhead by separating production and consumption data structure of buffer pool
소비용 buffer pool list와 생산용 buffer pool list를 따로두고,
기존의 생산 소비에 동일한 lock을 사용함으로 인해 발생하는 lock overhead를 줄임, 
소비 pool list가 소진되면 생산 pool list와 swap함. (threshold두어 어느정도 생산 pool list에 채워졌을때만 swap 하도록 하여 빈번한 swap오버헤드 줄임)
+ 불필요한 method 제거
+ GC Bufferpool 2배 증가
Signed-off-by: minjoon.ahn <minjoon.ahn@samsung.com>
=> [AWIBOF-7372] minimize lock overhead for buffer pool

src/metafs/common/meta_file_util.cpp, src/metafs/common/meta_file_util.h, test/unit-tests/metafs/common/meta_file_util_test.cpp
- if mfs_dump_files_list wbt command is issued with volume type 2, the crash will be occured
- changed the converting method between volume types and their names
=> [AWIBOF-7471] fix assert of metafs

lib/spdk-22.01.1.patch
admin_qpair nullptr occured during adding io qpair to ctrlr.
Ctrlr was in destruct process due to expiration of keep alive timer.
While destructing the admin_qpair, io command came in and got into nullptr error.
Signed-off-by: syeon.shin <syeon.shin@samsung.com>
=> [AWIBOF-7476] Fix admin_qpair nullptr error

src/metafs/mim/mio.cpp, src/metafs/mim/mio.h, src/metafs/mim/mpio_allocator.cpp, src/metafs/mim/mpio_allocator.h, test/unit-tests/metafs/mim/mpio_allocator_mock.h
- when mpio is full and new mpio wants to be pushed to the cache, an assert in mpio_allocator occurs
=> [SHPOS-977] add waiting for free cache space

config/pos.conf, src/logger/configuration.cpp, src/logger/configuration.h, src/logger/logger.h, src/logger/preferences.cpp, src/logger/preferences.h, src/metafs/metafs_service.cpp, test/unit-tests/logger/logger_test.cpp
Add BurstFilter to logger.
**Background**
Previously, although a number of the same events occur, the old logger logged all the duplicated events.
This was problematic because the huge number of event logs severely degraded the readability of the log.
To mitigate the problem, this commit implements BurstFilter.
**BurstFilter**
When the same events occur repeatedly, the new logger with BurstFilter does not log the event. Instead, it stores the event's ID, message, and the repetition count.
The duplicated events are logged to the file when
- A new (different) event occurs
- The number of duplicated events becomes greater than BurstFilter window size
Add enable_burst_filter and burst_filter_window_size to pos.conf
=> [AWIBOF-7399] Add burst filter to logger

src/allocator/block_manager/block_manager.cpp, src/allocator/block_manager/block_manager.h, src/allocator/context_manager/block_allocation_status.cpp, src/allocator/context_manager/block_allocation_status.h, src/allocator/i_block_allocator.h, src/event_scheduler/callback.cpp, src/io/backend_io/stripe_map_update_request.cpp, src/io/frontend_io/write_submission.cpp, test/unit-tests/allocator/block_manager/block_manager_mock.h, test/unit-tests/allocator/i_block_allocator_mock.h
1) Remove Error Log to reduce GC overhead
2) Check Urgent state before locking rba in write submission
=> [AWIBOF-7505] remove error log and add check urgent before locking rba

src/device/device_manager.cpp, src/device/device_manager.h
Lock 내에서 RemoveDeviceForReactor를 하지 못하게 Lock scope를 줄인 change입니다.
=> [SHPOS-1024] Remove deadlock in device manager

config/publication_list_default.yaml, src/allocator/allocator.cpp, src/gc/copier_meta.cpp, src/gc/copier_meta.h, src/gc/copier_read_completion.cpp, src/gc/flow_control/flow_control.cpp, src/gc/gc_flush_completion.cpp, src/gc/gc_flush_submission.cpp, src/gc/gc_map_update_completion.cpp, src/gc/gc_stripe_manager.cpp, src/gc/gc_stripe_manager.h, src/gc/stripe_copier.cpp, src/io/general_io/rba_state_manager.cpp, src/resource_manager/buffer_pool.cpp, src/resource_manager/buffer_pool.h, src/telemetry/telemetry_id.h, test/unit-tests/gc/copier_meta_mock.h, test/unit-tests/gc/gc_flush_completion_test.cpp, test/unit-tests/gc/gc_stripe_manager_mock.h, test/unit-tests/gc/stripe_copier_test.cpp, test/unit-tests/resource_manager/buffer_pool_mock.h
GC stripe force flush시 잘못된 vol_id 전달로 인한 exception case 수정
GC THRESHOLD 설정 오류 수정
Flow control 모듈등의 로그에 array id 누락되어 추가
Read buffer 여러개 획득시 한번의 lock획득으로 일괄 획득하도록 버퍼풀 로직 수정
GC flushing count / map updating count를 telemetry metrics로 추가
=> fixed an exception due to invalid volume id when performing GC strip force flush

src/cli/grpc_cli_server.cpp, src/cli/grpc_cli_server.h, src/logger/logger.h
Insert CLI command name in the CLI event log to improve the readability of the log.
=> [AWIBOF-7550] Insert CLI command name in the CLI event log

src/allocator/wbstripe_manager/wbstripe_manager.cpp, src/journal_manager/replay/replay_log_list.cpp, test/unit-tests/journal_manager/replay/replay_log_list_test.cpp
- fixed the seg fault that occurs when array mount and unmount are repeated
=> [SHPOS-1032] Change the location where stripeLoadStatus is created

src/allocator/stripe_manager/wbstripe_manager.cpp, test/unit-tests/allocator/stripe_manager/wbstripe_manager_test.cpp
Update allocator context at last when freeing stripe so that anybody allocating wbstripe never sees non-empty wbStripeArray after get it from allocator context
=> [AWIBOF-7691] Fix concurrency issue in allocating and freeing wb stripe

src/allocator/context_manager/segment_ctx/segment_ctx.cpp, src/allocator/context_manager/segment_ctx/segment_ctx.h, src/allocator/context_manager/segment_ctx/segment_info.cpp, src/allocator/context_manager/segment_ctx/segment_info.h, src/journal_manager/log_buffer/i_versioned_segment_context.h, src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_buffer/versioned_segment_ctx.h, test/integration-tests/allocator/context_manager_integration_test.cpp, test/integration-tests/segmentCtx/segment_ctx_integration_test.cpp, test/integration-tests/segmentCtx/segment_ctx_tester.h, test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_mock.h, test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_test.cpp, test/unit-tests/allocator/context_manager/segment_ctx/segment_info_mock.h, test/unit-tests/allocator/context_manager/segment_ctx/segment_info_test.cpp, test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp
- Bug scenario : To support backward compatibility, loading metadata among different POS binary must be possible. But loading Object including virtual methods causes corruption.
- Solution : Save only data not object including virtual methods.
- Added UT/IT fix
- fixed VersionedSegmentCtx memory issue
----------------------------------------------------------------------
Backward Compatibility 지원에 있어서 문제가 되었던 부분을 수정했습니다.
기존 문제 상황 
- 커밋 1 (이해하기 쉽게 커밋 해시를 1,2 로 표현하겠습니다.) 에서 빌드하고 Array 생성 및 mount 하여 IO를 실행
- Array에 저장되는 데이터와 관계 없는 소스코드 변경을 포함한 커밋 2 추가 및 동일 머신에서 빌드
- 커밋 2의 포세이돈을 실행하여 커밋 1에서 저장된 Array를 dirty bringup 시도
- **예측은 정상 실행 되어야하나 데이터 관련 변경점이 없는 상황임에도 불구하고 dirty bringup 실패** 
문제 해결에 대한 변경사항
- 기존에 Object 전체를 memcpy하는 방식(virtual table 까지 복사)에서 Object 내부의 Data만 복사하여 저장하는 방식으로 변경
- 문제 상황은 …
=> [AWIBOF-7453] store only SegmentInfoData instead of storing SegmentInfo Object

test/regression/tc_lib_ci.sh
fix Sending the signal timing after process is not initialized.
=> [AWIBOF-8158] fix signal test in post commit test

src/journal_manager/log_buffer/log_write_io_context.cpp, test/unit-tests/journal_manager/log_buffer/log_write_io_context_test.cpp
Call client callback event first and then notify journal sub-modules that log write is done when journal log write is completed, so that journal internal events(e.g., checkpoint) can be triggered after all log write is completely done.
=> [AWIBOF-8031] Change log write done sequence

script/pkgdep.sh, src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_buffer/versioned_segment_info.cpp, src/journal_manager/log_buffer/versioned_segment_info.h, src/metadata/segment_context_updater.cpp, src/metadata/segment_context_updater.h, test/CMakeLists.txt, test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp, test/unit-tests/journal_manager/log_buffer/versioned_segment_info_mock.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_info_test.cpp
- Changed variables in Versioned Segment Context Info to atomic
- Added unit test to modify Versioned Segment Context Info on multi-thread
=> [AWIBOF-8105] Remove lock on the Segment Context Updater

src/journal_manager/journal_manager.cpp, src/journal_manager/log_buffer/i_versioned_segment_context.h, src/journal_manager/log_buffer/versioned_segment_ctx.cpp, src/journal_manager/log_buffer/versioned_segment_ctx.h, src/journal_manager/replay/load_replayed_segment_context.cpp, src/journal_manager/replay/load_replayed_segment_context.h, src/journal_manager/replay/replay_handler.cpp, src/journal_manager/replay/replay_handler.h, src/journal_manager/replay/replay_progress_reporter.cpp, test/integration-tests/allocator/context_manager_integration_test.cpp, test/unit-tests/journal_manager/log_buffer/i_versioned_segment_context_mock.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_mock.h, test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp, test/unit-tests/journal_manager/replay/replay_handler_mock.h, test/unit-tests/journal_manager/replay/replay_handler_test.cpp, test/unit-tests/journal_manager/replay/replay_progress_reporter_mock.h
[Revieweee]
- Review 목적: VSC Load 시점을 Replay 가 모두 끝난 뒤로 옮기기
- 참고 문서: IMS
- 주요 review 파일: versioned_segment_ctx.cpp, load_versioned_segment_context.cpp
- 검증 방법 또는 TC: UT/IT
[Reviewer]
- Checklist
=> [AWIBOF-8118] Add replay task to load Versieond Segment Context from updated segment context

doc/development/telemetry/ID_RULES.md, doc/development/telemetry/METRICS.md, src/telemetry/telemetry_air/telemetry_air_delegator.cpp, src/telemetry/telemetry_air/telemetry_air_delegator.h, src/telemetry/telemetry_id.h
Add reactor utilzation metric to telemetry
It shows reactor virtual time spent on (idle, busy) and collected by AIR as metric name UTIL_REACTOR
=> [AWIBOF-7524] Add reactor utilization metric to telemetry

src/bio/ubio.h, src/device/device_manager.cpp, src/device/directive_cmd.cpp, src/device/directive_cmd.h, src/device/unvme/unvme_cmd.cpp, src/device/unvme/unvme_cmd.h, src/spdk_wrapper/caller/spdk_nvme_caller.cpp, src/spdk_wrapper/caller/spdk_nvme_caller.h
enable NVMe directive cmd and divide write streams for user, meta, journal
Signed-off-by: yongjin.lee yong7.lee@samsung.com
=> [AWIBOF-7478] Enable nvme directive cmd for multistream

config/pos.conf, src/main/poseidonos.cpp
If the save_restore option is true in pos.conf, it will look for the /etc/pos/restore.json file and try to restore it, and save the CLI command if the file does not exist or if it succeeds.
=> [AWIBOF-8163] Add option to enable save/restore function

config/ibofos_for_perf_ci.conf, config/ibofos_for_perf_ci_single_numa.conf, config/ibofos_for_perf_psd.conf, config/ibofos_for_perf_psd_200GB.conf, config/ibofos_for_psd_ci.conf, config/ibofos_for_psd_ci_wt.conf, config/ibofos_for_vm_ci.conf, config/ibofos_for_vm_ci_wt.conf, config/pos.conf, config/pos_for_aws.conf, config/pos_for_ha_primary_psd.conf, config/pos_for_ha_secondary_psd.conf, config/pos_for_pm_qos.conf, config/pos_multi_array_fast_sustain_perf.conf, config/pos_multi_array_normal.conf, config/pos_multi_array_perf.conf
Why:
- Ensure correct replay of segment context after SPO during the checkpoint
- Prevent overflow or underflow of valid block count and occupied segment count
What:
- Modify config to enable Versioned Segment Context by default
This commit modifies the code to enable Versioned Segment Context (VSC) by default. When VSC is disabled and an SPO occurs during checkpoint, the segment context may be double replayed because the most recent SegmentContext can be flushed along with the log group being checkpointed. This can cause valid block count and occupied stripe count to overflow or underflow during replay. By enabling VSC by default, we can ensure that the correct segment context is reconstructed after an SPO checkpoint and prevent these issues from occurring
=> [AWIBOF-7879] Enable Versioned Segment Context by default

src/event/pos_event.yaml, src/mapper/reversemap/reversemap_manager.cpp, src/mapper/reversemap/reversemap_manager.h, test/unit-tests/mapper/reversemap/reversemap_manager_test.cpp
- steps
= construct inverted map from the latest vsamap
= verify revMapInfos from the log buffer
= look up the rba
=> [AWIBOF-7875] Change the logic of searching RBA during bringup (#752)

src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
Lock allocCtxLock and then lock activeStripeTailLock may introduce deadlock as these locks can be acquired in a reverse order.
When copying data for flush(BeforeFlush), we don't have to acquire both locks at the same time, so removing this overlap
=> [AWIBOF-8258] Do not acquire allocCtxLock and activeStripeTailLock in wrong seqeunce
